import Link from 'next/link'
import ActionForm from '@/app/admin/components/ActionForm'
import {provisionSiteAction} from '../actions'
import {PERMISSIONS,requirePermission} from '@/lib/authz/permissions'
import {getAdminLocale} from '@/lib/i18n/admin-locale'

export default async function NewPlatformSitePage(){
  const locale=await getAdminLocale(),l=(fa:string,en:string)=>locale==='fa'?fa:en
  await requirePermission(PERMISSIONS.PLATFORM_ORGANIZATIONS_MANAGE)
  return <main className="admin-shell"><div className="admin-head"><div><span className="eyebrow">{l('مرحله ۱ از ۵','STEP 1 OF 5')}</span><h1>{l('ساخت سایت جدید','Create a new site')}</h1><p>{l('فقط اطلاعاتی را وارد کنید که برای شروع لازم است. شناسه‌ها، محیط‌ها، واحد پول و تنظیمات فنی را راوا به‌صورت امن آماده می‌کند.','Enter only what is needed to begin. RAVA securely prepares identifiers, environments, currency, and technical settings.')}</p></div><Link className="admin-muted-button" href="/admin/platform/sites">{l('بازگشت','Back')}</Link></div><section className="admin-panel"><ActionForm action={provisionSiteAction} className="admin-form" confirmTitle={l('ساخت سایت','Create site')} confirmMessage={l('ساختار امن سایت آماده شود و سپس به مرحله انتخاب محتوای کسب‌وکار برویم؟','Prepare the secure site structure and continue to business content selection?')} confirmLabel={l('بله، سایت آماده شود','Yes, prepare the site')}><label>{l('نام مشتری یا کسب‌وکار','Customer or business name')}<input name="organization_name" required minLength={2} maxLength={120} autoComplete="organization" placeholder={l('برای نمونه: شرکت آفتاب','For example: Sun Company')}/><small>{l('نامی که در قرارداد و مدیریت مشتری می‌بینید.','The name used in customer management and contracts.')}</small></label><label>{l('نام سایت','Site name')}<input name="site_name" minLength={2} maxLength={120} placeholder={l('اگر خالی بماند، نام کسب‌وکار استفاده می‌شود.','The business name is used if this is left empty.')}/><small>{l('فقط وقتی یک مشتری چند سایت یا برند دارد، نام متفاوت وارد کنید.','Use a different name only when the customer has multiple sites or brands.')}</small></label><label>{l('زبان اصلی سایت','Primary site language')}<select name="primary_locale" defaultValue="fa"><option value="fa">{l('فارسی','Persian')}</option><option value="en">{l('انگلیسی','English')}</option></select></label><div className="admin-empty">{l('پس از این مرحله، محتوای آماده متناسب با حوزه کسب‌وکار را انتخاب می‌کنید. هیچ چیزی به‌صورت عمومی منتشر نمی‌شود.','Next, you will choose ready-made content for the business field. Nothing is published publicly.')}</div><button className="admin-primary-button" type="submit">{l('ساخت سایت و رفتن به مرحله بعد','Create site and continue')}</button></ActionForm></section></main>
}
