import type{CSSProperties}from'react';import {createClient} from '@/lib/supabase/server'
export type ThemeTokens={color?:{background?:string;surface?:string;text?:string;muted?:string;accent?:string;border?:string};radius?:{sm?:number;md?:number;lg?:number};layout?:{container?:number;sectionGap?:number};motion?:{intensity?:number};typography?:{faFamily?:string;enFamily?:string;displayFamily?:string;baseSize?:number;scale?:number;lineHeight?:number;headingLineHeight?:number;weightBody?:number;weightHeading?:number;letterSpacing?:number}}
const SAFE_COLOR=/^(#[0-9a-f]{3,8}|rgba?\([0-9.,% ]+\)|hsla?\([0-9.,% ]+\))$/i
const SAFE_FONT=/^[a-z0-9 _-]{2,40}$/i
function color(v:unknown,fallback:string){return typeof v==='string'&&v.length<80&&SAFE_COLOR.test(v.trim())?v.trim():fallback}
function num(v:unknown,min:number,max:number,fallback:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback}
function font(v:unknown,fallback:string){return typeof v==='string'&&SAFE_FONT.test(v.trim())?v.trim():fallback}
export function themeCssVars(tokens:ThemeTokens={}){const c=tokens.color||{},r=tokens.radius||{},l=tokens.layout||{},m=tokens.motion||{},t=tokens.typography||{},bg=color(c.background,'#0b0f17'),surface=color(c.surface,'#111722'),text=color(c.text,'#f5f7fb'),muted=color(c.muted,'#9aa5b5'),accent=color(c.accent,'#5f7cff'),border=color(c.border,'rgba(255,255,255,.10)'),container=`${num(l.container,720,1800,1240)}px`;return {'--theme-bg':bg,'--theme-surface':surface,'--theme-text':text,'--theme-muted':muted,'--theme-accent':accent,'--theme-border':border,'--theme-radius-sm':`${num(r.sm,0,80,10)}px`,'--theme-radius-md':`${num(r.md,0,80,18)}px`,'--theme-radius-lg':`${num(r.lg,0,120,30)}px`,'--theme-container':container,'--theme-section-gap':`${num(l.sectionGap,24,240,96)}px`,'--theme-motion':String(num(m.intensity,0,2,1)),'--theme-font-fa':font(t.faFamily,'Vazirmatn'),'--theme-font-en':font(t.enFamily,'Inter'),'--theme-font-display':font(t.displayFamily,'Inter'),'--theme-font-base':`${num(t.baseSize,13,22,16)}px`,'--theme-type-scale':String(num(t.scale,1.05,1.6,1.25)),'--theme-line-height':String(num(t.lineHeight,1.2,2.2,1.75)),'--theme-heading-line-height':String(num(t.headingLineHeight,.9,1.6,1.15)),'--theme-weight-body':String(num(t.weightBody,300,700,400)),'--theme-weight-heading':String(num(t.weightHeading,500,900,700)),'--theme-letter-spacing':`${num(t.letterSpacing,-.08,.2,0)}em`,'--bg':bg,'--surface':surface,'--text':text,'--muted':muted,'--primary':accent,'--accent':accent,'--line':border,'--container':container} as CSSProperties}
export function adminSkinCssVars(tokens:ThemeTokens={}){const c=tokens.color||{},r=tokens.radius||{};return {'--admin-accent':color(c.accent,'#5f7cff'),'--admin-brand-surface':color(c.surface,'#111722'),'--admin-brand-border':color(c.border,'rgba(255,255,255,.10)'),'--admin-brand-radius':`${num(r.md,8,32,18)}px`} as CSSProperties}
export async function getPublishedTheme(tenantId:string){const s=await createClient();const{data}=await s.from('tenant_theme_settings').select('theme_key,published_tokens,published_variants,admin_skin_sync').eq('tenant_id',tenantId).maybeSingle();return data||null}
