import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { hasPermission, PERMISSIONS, requirePermission } from '@/lib/authz/permissions'
import ActionForm from '../../components/ActionForm'
import MediaPicker from '../../components/MediaPicker'
import { createBlock, deleteBlock, deletePage, moveBlock, toggleBlock, updateBlock, updatePage } from '../actions'
import {getAdminLocale} from '@/lib/i18n/admin-locale'
import SeoAssistant from './SeoAssistant'
import SiteDraftPreview from '../../components/SiteDraftPreview'

export const dynamic = 'force-dynamic'
export default async function PageEditor({params}:{params:Promise<{id:string}>}){
 const locale=await getAdminLocale(),l=(fa:string,en:string)=>locale==='fa'?fa:en;const names:Record<string,string>={hero:l('بخش آغازین','Hero'),text:l('متن','Text'),image:l('تصویر','Image'),cta:l('دعوت به اقدام','Call to action'),gallery:l('گالری','Gallery')}
 const{id}=await params;const supabase=await createClient();const{data:claimsData}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub;if(!userId)redirect('/login');const{data:profile}=await supabase.from('profiles').select('active').eq('id',userId).single();if(!profile?.active)redirect('/login');
 const{data:page}=await supabase.from('pages').select('id,site_id,title,slug,status,seo').eq('id',id).single();if(!page?.site_id)notFound();const{data:site}=await supabase.from('sites').select('id,organization_id,name').eq('id',page.site_id).maybeSingle();if(!site)notFound();await requirePermission(PERMISSIONS.CMS_MANAGE,{organizationId:site.organization_id,siteId:site.id});const seo=(page.seo??{})as{title?:string;description?:string};
 const[{data:blocks},aiEnabled]=await Promise.all([supabase.from('page_blocks').select('id,block_type,position,visible,data').eq('page_id',id).order('position',{ascending:true}),hasPermission(PERMISSIONS.PLATFORM_SITES_MANAGE,{organizationId:site.organization_id,siteId:site.id})]);
 return <main className="admin-shell">
  <header className="admin-head"><div><span>{l('مرکز مدیریت راوا','RAVA CONTROL CENTER')}</span><h1>{l('ویرایش صفحه','Edit page')}</h1><p>{l('سایت فعال:','Active site:')} <b>{site.name}</b></p></div><div className="admin-actions"><Link className="admin-link" href={`/admin/pages?site=${site.id}`}>{l('بازگشت به صفحه‌ها','Back to pages')}</Link></div></header>
  <section className="admin-panel"><div className="admin-section-title"><div><h2>{l('پیش‌نمایش واقعی همین صفحه','Real preview of this page')}</h2><p>{l('پیش‌نویس را با ظاهر نهایی سایت ببینید؛ این نمایش عمومی نیست.','Review the draft with the final site design. This preview is not public.')}</p></div><span>{l('خصوصی','Private')}</span></div><SiteDraftPreview siteId={site.id} pages={[{id:page.id,title:page.title}]} initialPageId={page.id}/></section>
  <section className="admin-panel"><ActionForm action={updatePage} className="admin-form" confirmTitle={l('ذخیره تغییرات صفحه','Save page changes')} confirmMessage={l(`تغییرات صفحه «${page.title}» ذخیره شود؟`,`Save changes to “${page.title}”?`)} confirmLabel={l('بله، تغییرات ذخیره شود','Yes, save changes')}><input type="hidden" name="id" value={page.id}/><div className="admin-grid-2"><label>{l('عنوان صفحه','Page title')}<input name="title" defaultValue={page.title} required/><small>{l('نامی که بازدیدکننده داخل سایت می‌بیند.','The name visitors see on the website.')}</small></label><label>{l('آدرس صفحه','Page address')}<input name="slug" defaultValue={page.slug} required dir="ltr"/><small>{l('کوتاه، با نویسه‌های لاتین و بدون فاصله باشد.','Short, lowercase and without spaces; for example services')}</small></label></div><label>{l('وضعیت صفحه','Page status')}<select name="status" defaultValue={page.status}><option value="draft">{l('پیش‌نویس — فقط داخل پنل','Draft — admin only')}</option><option value="published">{l('منتشرشده — قابل مشاهده برای همه','Published — publicly visible')}</option><option value="hidden">{l('مخفی — موقتاً خارج از سایت','Hidden — temporarily unavailable')}</option></select><small>{l('انتشار عمومی نیازمند دسترسی جداگانه است.','Public publishing requires a separate permission.')}</small></label><SeoAssistant pageId={page.id} siteName={site.name} initialTitle={seo.title??''} initialDescription={seo.description??''} aiEnabled={aiEnabled}/><div className="admin-save-row"><button type="submit">{l('ذخیره تغییرات','Save changes')}</button><a className="admin-link" href={`/preview/sites/${site.id}?page=${page.id}`} target="_blank">{l('پیش‌نمایش واقعی صفحه','Preview page')}</a></div></ActionForm></section>

  <section className="admin-panel"><h2>{l('صفحه‌ساز','Page builder')}</h2><p>{l('بخش‌های صفحه را بسازید، ویرایش کنید، مرتب کنید یا مخفی کنید.','Create, edit, arrange, or hide page sections.')}</p><ActionForm action={createBlock} className="admin-form" confirmTitle={l('افزودن بخش','Add section')} confirmMessage={l('این بخش به انتهای صفحه اضافه شود؟','Add this section to the end of the page?')} confirmLabel={l('بله، اضافه شود','Yes, add section')}><input type="hidden" name="page_id" value={page.id}/><div className="admin-grid-2"><label>{l('نوع بخش','Section type')}<select name="block_type">{Object.entries(names).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="admin-save-row"><button type="submit">{l('+ افزودن بخش','+ Add section')}</button></div></div></ActionForm></section>

  {(blocks??[]).map((block,index)=>{const d=(block.data??{})as Record<string,unknown>;return <section className="admin-panel" key={block.id}><div className="admin-head"><div><span>{l('بخش','SECTION')} {index+1}</span><h2>{names[block.block_type]??block.block_type} {!block.visible?l('— مخفی','— Hidden'):''}</h2></div></div>
   <ActionForm action={updateBlock} className="admin-form" confirmTitle={l('ویرایش بخش','Edit section')} confirmMessage={l(`تغییرات بخش ${names[block.block_type]??block.block_type} ذخیره شود؟`,`Save changes to the ${names[block.block_type]??block.block_type} section?`)} confirmLabel={l('بله، ذخیره شود','Yes, save')}><input type="hidden" name="id" value={block.id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="block_type" value={block.block_type}/>
    {(block.block_type==='hero'||block.block_type==='text'||block.block_type==='cta')&&<><label>{l('عنوان','Title')}<input name="title" defaultValue={String(d.title??'')}/></label><label>{l('متن','Text')}<textarea name="text" rows={5} defaultValue={String(d.text??'')}/></label></>}
    {(block.block_type==='hero'||block.block_type==='cta')&&<div className="admin-grid-2"><label>{l('متن دکمه','Button label')}<input name="button_label" defaultValue={String(d.button_label??'')}/></label><label>{l('پیوند دکمه','Button link')}<input name="button_url" dir="ltr" defaultValue={String(d.button_url??'')}/></label></div>}
    {block.block_type==='image'&&<><label>{l('تصویر','Image')}<MediaPicker name="url" siteId={site.id} defaultValue={String(d.url??'')}/></label><div className="admin-grid-2"><label>{l('متن جایگزین تصویر','Image alternative text')}<input name="alt" defaultValue={String(d.alt??'')}/></label><label>{l('زیرنویس','Caption')}<input name="caption" defaultValue={String(d.caption??'')}/></label></div></>}
    {block.block_type==='gallery'&&<><label>{l('عنوان گالری','Gallery title')}<input name="title" defaultValue={String(d.title??'')}/></label><label>{l('نشانی تصاویر؛ هر خط یک تصویر','Image URLs; one per line')}<textarea name="images" dir="ltr" rows={6} defaultValue={Array.isArray(d.images)?d.images.join('\n'):''}/></label></>}
    <button type="submit">{l('ذخیره این بخش','Save section')}</button></ActionForm>
    <div className="admin-grid-2" style={{marginTop:'1rem'}}><ActionForm action={toggleBlock} confirmTitle={block.visible?l('مخفی‌کردن بخش','Hide section'):l('نمایش بخش','Show section')} confirmMessage={l('وضعیت نمایش این بخش تغییر کند؟','Change this section’s visibility?')}><input type="hidden" name="id" value={block.id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="visible" value={String(block.visible)}/><button type="submit" className="admin-muted-button">{block.visible?l('مخفی کن','Hide'):l('نمایش بده','Show')}</button></ActionForm><div className="admin-actions"><ActionForm action={moveBlock} confirmTitle={l('جابه‌جایی بخش','Move section')} confirmMessage={l('این بخش یک ردیف بالاتر برود؟','Move this section up one position?')}><input type="hidden" name="id" value={block.id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="direction" value="up"/><button type="submit" className="admin-muted-button">↑ {l('بالا','Up')}</button></ActionForm><ActionForm action={moveBlock} confirmTitle={l('جابه‌جایی بخش','Move section')} confirmMessage={l('این بخش یک ردیف پایین‌تر برود؟','Move this section down one position?')}><input type="hidden" name="id" value={block.id}/><input type="hidden" name="page_id" value={page.id}/><input type="hidden" name="direction" value="down"/><button type="submit" className="admin-muted-button">↓ {l('پایین','Down')}</button></ActionForm></div></div>
    <ActionForm action={deleteBlock} danger confirmTitle={l('حذف بخش','Delete section')} confirmMessage={l('این بخش و محتوای آن برای همیشه حذف شود؟','Permanently delete this section and its content?')} confirmLabel={l('بله، حذف شود','Yes, delete')}><input type="hidden" name="id" value={block.id}/><input type="hidden" name="page_id" value={page.id}/><button className="admin-danger-button" type="submit">{l('حذف بخش','Delete section')}</button></ActionForm>
   </section>})}

  <section className="admin-panel admin-danger-zone"><h2>{l('حذف صفحه','Delete page')}</h2><p>{l('این عملیات صفحه و تمام بخش‌های آن را برای همیشه حذف می‌کند.','This permanently deletes the page and all of its sections.')}</p><ActionForm action={deletePage} danger confirmTitle={l('حذف کامل صفحه','Delete page permanently')} confirmMessage={l(`صفحه «${page.title}» و تمام محتوای آن برای همیشه حذف شود؟`,`Permanently delete “${page.title}” and all its content?`)} confirmLabel={l('بله، برای همیشه حذف شود','Yes, delete permanently')}><input type="hidden" name="id" value={page.id}/><button className="admin-danger-button" type="submit">{l('حذف کامل صفحه','Delete page permanently')}</button></ActionForm></section>
 </main>
}
