'use client'

import {useState,useTransition} from 'react'
import {requestSeoSuggestion,type SeoSuggestionState} from '../seo-actions'
import {useAdminLocale} from '../../components/AdminLocale'

export default function SeoAssistant({pageId,siteName,initialTitle,initialDescription,aiEnabled}:{pageId:string;siteName:string;initialTitle:string;initialDescription:string;aiEnabled:boolean}){
 const {language}=useAdminLocale(),isFa=language==='fa'
 const [title,setTitle]=useState(initialTitle),[description,setDescription]=useState(initialDescription),[result,setResult]=useState<SeoSuggestionState|null>(null),[pending,startTransition]=useTransition()
 const l=(fa:string,en:string)=>isFa?fa:en,count=(value:string)=>Array.from(value).length
 const suggest=()=>startTransition(async()=>setResult(await requestSeoSuggestion(pageId)))
 return <section className="rava-seo-card" aria-labelledby="seo-card-title"><header><div><span>{l('نمایش در موتورهای جست‌وجو','Search appearance')}</span><h2 id="seo-card-title">{l('پیش‌نمایش صفحه در گوگل','Google result preview')}</h2><p>{l('عنوان و توضیحی بنویسید که دقیق و قابل‌فهم باشد. گوگل ممکن است متن دیگری را نمایش دهد.','Write an accurate, readable title and description. Google may choose different text.')}</p></div>{aiEnabled?<button className="rava-ai-button" type="button" disabled={pending} onClick={suggest}>{pending?l('در حال ساخت پیشنهاد…','Generating suggestion…'):l('پیشنهاد هوشمند','AI suggestion')}</button>:null}</header><div className="rava-google-preview" dir={isFa?'rtl':'ltr'}><small>{siteName}</small><strong>{title||l('عنوان صفحه در گوگل','Google page title')}</strong><span>{description||l('توضیح کوتاه و دقیق صفحه در این قسمت دیده می‌شود.','A concise and accurate page description appears here.')}</span></div><div className="admin-grid-2"><label>{l('عنوان صفحه در گوگل','Google page title')}<input name="seo_title" value={title} maxLength={70} onChange={event=>setTitle(event.target.value)}/><small className={count(title)>60?'is-warning':''}>{count(title)} / 60 · {l('پیشنهاد: کوتاه، دقیق و یکتا','Recommended: concise, accurate and unique')}</small></label><label>{l('توضیح صفحه در گوگل','Google page description')}<textarea name="seo_description" value={description} maxLength={180} rows={4} onChange={event=>setDescription(event.target.value)}/><small className={count(description)>160?'is-warning':''}>{count(description)} / 160 · {l('فایده صفحه و قدم بعدی مخاطب را توضیح دهید','Explain the page value and the visitor’s next step')}</small></label></div>{result?<div className={`rava-ai-result ${result.ok?'is-success':'is-error'}`} role="status"><p>{result.message}</p>{result.suggestion?<><div className="rava-ai-diff"><div><small>{l('پیشنهاد عنوان','Suggested title')}</small><b>{result.suggestion.title}</b></div><div><small>{l('پیشنهاد توضیح','Suggested description')}</small><span>{result.suggestion.description}</span></div><div><small>{l('عبارت اصلی پیشنهادی','Suggested focus phrase')}</small><span>{result.suggestion.focusKeyword}</span></div><div><small>{l('دلیل پیشنهاد','Why this suggestion')}</small><span>{result.suggestion.reasoning}</span></div></div><button type="button" className="admin-primary-button" onClick={()=>{setTitle(result.suggestion!.title);setDescription(result.suggestion!.description)}}>{l('قرار دادن در فیلدها','Apply to fields')}</button></>:null}</div>:null}</section>
}
