import type {CSSProperties,ReactNode} from 'react'
import Link from 'next/link'
import type {PublicBlock,PublicPagePayload} from '@/lib/cms/public-runtime'
import JourneyNavigation from './JourneyNavigation'
import JourneyRail from './JourneyRail'
import styles from '@/app/[slug]/public-page.module.css'

export type PreviewNavigationItem={id:string;title:string;slug:string}
export const publicText=(value:unknown)=>typeof value==='string'?value.slice(0,10000):''
const items=(value:unknown)=>Array.isArray(value)?value.slice(0,24):[]
const object=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}
const safeUrl=(value:unknown)=>{const url=publicText(value).trim();return /^\/(?!\/)/.test(url)||/^#[a-zA-Z0-9_-]+$/.test(url)||/^https?:\/\//i.test(url)||/^mailto:/i.test(url)||/^tel:/i.test(url)?url:''}
const safeColor=(value:unknown)=>typeof value==='string'&&/^#[0-9a-f]{6}$/i.test(value)?value:''

function pageStyle(payload:PublicPagePayload):CSSProperties{const colors=payload.site.theme?.colors;if(!colors||typeof colors!=='object'||Array.isArray(colors))return{};const palette=colors as Record<string,unknown>;return{...(safeColor(palette.background||palette.paper)?{'--page-bg':safeColor(palette.background||palette.paper)}:{}),...(safeColor(palette.surface)?{'--page-surface':safeColor(palette.surface)}:{}),...(safeColor(palette.text||palette.ink)?{'--page-text':safeColor(palette.text||palette.ink)}:{}),...(safeColor(palette.primary)?{'--page-primary':safeColor(palette.primary)}:{}),...(safeColor(palette.accent)?{'--page-accent':safeColor(palette.accent)}:{})}as CSSProperties}
function ArrowIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24"><path d="M5 12h14M13 6l6 6-6 6"/></svg>}
function Cards({data,journey=false,isFa=false}:{data:Record<string,unknown>;journey?:boolean;isFa?:boolean}){const entries=items(data.items);if(!entries.length)return null;const normalized=entries.map((entry,index)=>{const item=typeof entry==='string'?{title:entry}:object(entry);return{title:publicText(item.title)||`${index+1}`,text:publicText(item.text||item.description)}});if(journey)return <JourneyRail items={normalized} isFa={isFa}/>;return <div className={styles.grid}>{normalized.map((item,index)=><article className={styles.card} key={`${item.title}:${index}`}><b>{item.title}</b>{item.text&&<span>{item.text}</span>}</article>)}</div>}

const journeyCopy={fa:{route:'مسیر همکاری',routeTitle:'یک مسیر روشن؛ از شناخت تا رشد',routeBody:'پیچیدگی فنی پشت صحنه می‌ماند. شما در هر مرحله خروجی را می‌بینید، بازخورد می‌دهید و بعد از تأیید حرکت می‌کنیم.',steps:[['شناخت دقیق','هدف، مخاطب و نیاز واقعی کسب‌وکار را مشخص می‌کنیم.'],['طراحی هدفمند','ساختار، محتوا و تجربه را برای یک تصمیم روشن می‌سازیم.'],['رشد پیوسته','سایت با کسب‌وکار شما توسعه پیدا می‌کند و قابل مدیریت می‌ماند.']],story:'فراتر از یک ظاهر زیبا',storyTitle:'یک وب‌سایت باید برای کسب‌وکار شما کار کند',storyBody:'طراحی حرفه‌ای، محتوای متناسب با حوزه و مدیریت ساده کنار هم قرار می‌گیرند؛ تا هر صفحه مخاطب را به قدم بعدی هدایت کند.',proof:'آنچه در تمام مسیر حفظ می‌شود',proofItems:[['شفافیت','قبل از هر تغییر، نتیجه را در پیش‌نمایش می‌بینید.'],['انعطاف‌پذیری','صفحه‌ها و محتوا بدون بازسازی پرهزینه توسعه پیدا می‌کنند.'],['مالکیت','اطلاعات، دامنه و محتوای کسب‌وکار متعلق به شماست.'],['پشتیبانی','زیرساخت برای نگهداری و رشد بلندمدت آماده می‌ماند.']]},en:{route:'How we work',routeTitle:'A clear path from discovery to growth',routeBody:'Technical complexity stays behind the scenes. You see the outcome, share feedback and approve each meaningful step before we move forward.',steps:[['Focused discovery','We align the real business goal, audience and requirements.'],['Purposeful design','Structure, content and experience support one clear decision.'],['Continuous growth','Your site evolves with the business and remains manageable.']],story:'Beyond a beautiful interface',storyTitle:'A website should work for your business',storyBody:'Professional design, industry-aware content and simple management work together so every page guides people toward the next step.',proof:'What stays true throughout the journey',proofItems:[['Clarity','Preview every meaningful change before it moves forward.'],['Flexibility','Expand pages and content without an expensive rebuild.'],['Ownership','Your business information, domain and content remain yours.'],['Support','The foundation stays ready for long-term care and growth.']]}} as const

function JourneyNarrative({isFa}:{isFa:boolean}){const copy=isFa?journeyCopy.fa:journeyCopy.en;return <><section className={styles.journeyRoute} aria-labelledby="journey-route-title"><div className={styles.sectionLead}><span>{copy.route}</span><h2 id="journey-route-title">{copy.routeTitle}</h2><p>{copy.routeBody}</p></div><ol className={styles.journeySteps}>{copy.steps.map(([title,text],index)=><li key={title}><span>{isFa?new Intl.NumberFormat('fa-IR').format(index+1):String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section><section className={styles.journeyStory}><div className={styles.journeyStoryArt} role="img" aria-label={isFa?'تصویرسازی مسیر طراحی و رشد دیجیتال':'Illustration of a digital design and growth journey'}/><div><span>{copy.story}</span><h2>{copy.storyTitle}</h2><p>{copy.storyBody}</p><Link className={styles.textLink} href={isFa?'/services':'/services-en'}>{isFa?'خدمات را ببینید':'Explore services'} <ArrowIcon/></Link></div></section><section className={styles.journeyProof}><div className={styles.sectionLead}><span>{isFa?'اصول همکاری':'Our promise'}</span><h2>{copy.proof}</h2></div><JourneyRail items={copy.proofItems.map(([title,text])=>({title,text}))} isFa={isFa} variant="dark"/></section></>}

function JourneyBlock({block,locale}:{block:PublicBlock;locale:string}){const isFa=locale.startsWith('fa'),d=block.data||{},title=publicText(d.title),body=publicText(d.text||d.body||d.description),link=safeUrl(d.button_url||d.url),label=publicText(d.button_label)||(isFa?'بیشتر بدانید':'Learn more');if(block.type==='hero')return <section className={`${styles.block} ${styles.hero}`}><div className={styles.heroContent}><span className={styles.eyebrow}>{isFa?'طراحی، محتوا و فناوری':'Design, content and technology'}</span><h1>{title}</h1>{body&&<p>{body}</p>}<div className={styles.heroActions}>{link?<Link className={styles.button} href={link}>{label}<ArrowIcon/></Link>:<Link className={styles.button} href={isFa?'/contact':'/contact-en'}>{isFa?'شروع یک گفت‌وگو':'Start a conversation'}<ArrowIcon/></Link>}<Link className={styles.secondaryButton} href={isFa?'/portfolio':'/portfolio-en'}>{isFa?'دیدن نمونه‌کارها':'View our work'}</Link></div></div><div className={styles.heroVisual} aria-hidden="true"><span className={styles.orbitOne}/><span className={styles.orbitTwo}/><b>{isFa?'از ایده':'FROM IDEA'}<small>{isFa?'تا تجربه‌ای ماندگار':'TO LASTING EXPERIENCE'}</small></b></div><span className={styles.scrollCue}>{isFa?'برای کشف بیشتر پیمایش کنید':'Scroll to discover'}</span></section>;if(block.type==='cta')return <section className={`${styles.block} ${styles.cta}`}><span className={styles.eyebrow}>{isFa?'قدم بعدی':'Your next step'}</span><h2>{title}</h2>{body&&<p>{body}</p>}<Link className={styles.button} href={link||(isFa?'/contact':'/contact-en')}>{link?label:(isFa?'برای مشاوره آماده‌ام':'I am ready to talk')}<ArrowIcon/></Link></section>;return <Block block={block} locale={locale} journey/>}

function Block({block,locale,journey=false}:{block:PublicBlock;locale:string;journey?:boolean}){const isFa=locale.startsWith('fa'),d=block.data||{},title=publicText(d.title),body=publicText(d.text||d.body||d.description),link=safeUrl(d.button_url||d.url),label=publicText(d.button_label)||(isFa?'بیشتر بدانید':'Learn more');if(block.type==='hero')return <section className={`${styles.block} ${styles.hero}`}><span className={styles.eyebrow}>{String(block.position+1).padStart(2,'0')}</span><h1>{title}</h1>{body&&<p>{body}</p>}{link&&<Link className={styles.button} href={link}>{label}</Link>}</section>;if(block.type==='image')return <section className={styles.block}>{link&&<img className={styles.media} src={link} alt={publicText(d.alt)} width="1180" height="720"/>}{publicText(d.caption)&&<span className={styles.caption}>{publicText(d.caption)}</span>}</section>;if(block.type==='gallery'){const images=items(d.images).map(safeUrl).filter(Boolean);return <section className={styles.block}>{title&&<h2>{title}</h2>}<div className={styles.gallery}>{images.map((image,index)=><img key={`${image}:${index}`} src={image} alt={publicText(items(d.alts)[index])} width="720" height="540" loading="lazy"/>)}</div></section>};if(block.type==='cta')return <section className={`${styles.block} ${styles.cta}`}><h2>{title}</h2>{body&&<p>{body}</p>}{link&&<Link className={styles.button} href={link}>{label}</Link>}</section>;if(['service_list','project_list','services','projects','steps','faq'].includes(block.type))return <section className={`${styles.block} ${journey?styles.journeyContentBlock:''}`}>{title&&<h2>{title}</h2>}{body&&<p>{body}</p>}<Cards data={d} journey={journey} isFa={isFa}/></section>;if(['text','legal','rich_text'].includes(block.type))return <section className={`${styles.block} ${journey?styles.journeyContentBlock:''}`}>{title&&<h2>{title}</h2>}{body&&<p>{body}</p>}</section>;if(block.type==='lead_form')return <section className={`${styles.block} ${styles.cta}`}><h2>{title||(isFa?'شروع گفتگو':'Start a conversation')}</h2><p>{isFa?'فرم امن تماس پس از فعال‌سازی بخش ارتباط با مشتری در اینجا نمایش داده می‌شود.':'The secure contact form appears here after the customer communication module is enabled.'}</p></section>;return null}
function Shell({children}:{children:ReactNode}){return <>{children}</>}

export default function PublicPageView({payload,navigation=[],previewBasePath}:{payload:PublicPagePayload;navigation?:PreviewNavigationItem[];previewBasePath?:string}){const isEnglishPage=payload.page.slug.endsWith('-en'),locale=isEnglishPage?'en':payload.site.locale||'fa',isFa=!isEnglishPage&&locale.startsWith('fa'),isJourney=payload.site.templateKey==='rava-service-journey',isJourneyHome=isJourney&&['home','home-en'].includes(payload.page.slug),localizedNavigation=navigation.filter(item=>item.slug.endsWith('-en')===isEnglishPage);return <div className={`${styles.page} ${isJourney?styles.journeyTemplate:''}`} style={pageStyle(payload)} lang={locale} dir={isFa?'rtl':'ltr'} data-template={payload.site.templateKey||'rava-service-minimal'}><a className={styles.skipLink} href="#main-content">{isFa?'رفتن به محتوای اصلی':'Skip to main content'}</a><header className={styles.header}><Link className={styles.brand} href={previewBasePath?`${previewBasePath}?page=${payload.page.id}`:'/'} aria-label={payload.site.name}>{payload.site.name}</Link>{localizedNavigation.length?(isJourney?<JourneyNavigation items={localizedNavigation} activeId={payload.page.id} previewBasePath={previewBasePath} isFa={isFa}/>:<nav className={styles.navigation} aria-label={isFa?'صفحه‌های سایت':'Site pages'}>{localizedNavigation.slice(0,8).map(item=><Link className={item.id===payload.page.id?styles.activeNavigation:undefined} aria-current={item.id===payload.page.id?'page':undefined} key={item.id} href={previewBasePath?`${previewBasePath}?page=${item.id}`:`/${item.slug}`}>{item.title}</Link>)}</nav>):null}<Link className={styles.headerCta} href={previewBasePath?`${previewBasePath}?page=${payload.page.id}`:(isFa?'/contact':'/contact-en')}>{isFa?'شروع همکاری':'Start a project'}<ArrowIcon/></Link></header><main className={styles.main} id="main-content">{payload.blocks.length?<Shell>{payload.blocks.map((block,index)=><div key={block.id}>{isJourney?<JourneyBlock block={block} locale={locale}/>:<Block block={block} locale={locale}/>} {isJourneyHome&&index===0?<JourneyNarrative isFa={isFa}/>:null}</div>)}</Shell>:<div className={styles.empty}>{isFa?'این صفحه هنوز محتوای قابل‌نمایش ندارد.':'This page does not have previewable content yet.'}</div>}</main><footer className={styles.footer}><div><b>{payload.site.name}</b><p>{isFa?'طراحی، محتوا و فناوری برای رشد ماندگار':'Design, content and technology for lasting growth'}</p></div><span>© {new Date().getUTCFullYear()} · {isFa?'تمام حقوق محفوظ است.':'All rights reserved.'}</span></footer></div>}
