'use server'
import{revalidatePath}from'next/cache';import{generateSeo}from'@/lib/seo/engine';import{logEvent}from'@/lib/observability/logger';import{getTenantContext,hasManagedService}from'@/lib/platform/tenant-context';import{canRunManagedSeo}from'@/lib/platform/capabilities'
async function seoContext(){const a=await getTenantContext();const{data:allowed}=await a.s.rpc('can_manage_tenant_seo',{p_tenant_id:a.tenantId});if(!allowed)throw new Error('seo_access_denied');return a}
async function managed(){const a=await seoContext();if(!canRunManagedSeo(a))throw new Error('managed_seo_staff_only');if(!await hasManagedService(a.tenantId,'managed_seo'))throw new Error('managed_seo_not_entitled');return a}
function manualPayload(f:FormData){return{title:String(f.get('seo_title')||'').trim().slice(0,180),description:String(f.get('seo_description')||'').trim().slice(0,500),auto_generated:false,updated_at:new Date().toISOString()}}
export async function savePageSeo(f:FormData){const a=await seoContext(),id=String(f.get('id')||'');if(!id)return;const{error}=await a.s.rpc('set_page_seo',{p_tenant_id:a.tenantId,p_page_id:id,p_seo:manualPayload(f)});if(error)await logEvent({tenantId:a.tenantId,category:'error',eventName:'seo.page.manual.failed',actorUserId:a.userId,error,metadata:{page_id:id}});revalidatePath('/admin/seo')}
export async function saveProjectSeo(f:FormData){const a=await seoContext(),id=String(f.get('id')||'');if(!id)return;const{error}=await a.s.rpc('set_project_seo',{p_tenant_id:a.tenantId,p_project_id:id,p_seo:manualPayload(f)});if(error)await logEvent({tenantId:a.tenantId,category:'error',eventName:'seo.project.manual.failed',actorUserId:a.userId,error,metadata:{project_id:id}});revalidatePath('/admin/seo')}
export async function generatePageSeo(f:FormData){const a=await managed(),id=String(f.get('id')||''),{data:p}=await a.s.from('pages').select('title,slug,seo').eq('tenant_id',a.tenantId).eq('id',id).single();if(!p)return;const{data:blocks}=await a.s.from('page_blocks').select('data').eq('tenant_id',a.tenantId).eq('page_id',id).eq('visible',true).order('position'),body=(blocks||[]).map((b:any)=>[b.data?.title,b.data?.text,b.data?.caption].filter(Boolean).join(' ')).join(' '),x=generateSeo({title:p.title,slug:p.slug,body}),payload={...(p.seo||{}),title:x.title,description:x.description,auto_generated:true,score:x.score,generated_at:new Date().toISOString()},{error}=await a.s.rpc('set_page_seo',{p_tenant_id:a.tenantId,p_page_id:id,p_seo:payload});if(error)await logEvent({tenantId:a.tenantId,category:'error',eventName:'seo.page.generate.failed',actorUserId:a.userId,error,metadata:{page_id:id}});revalidatePath('/admin/seo')}
export async function generateProjectSeo(f:FormData){const a=await managed(),id=String(f.get('id')||''),{data:p}=await a.s.from('projects').select('title,slug,summary,seo').eq('tenant_id',a.tenantId).eq('id',id).single();if(!p)return;const x=generateSeo({title:p.title,slug:p.slug,summary:p.summary}),payload={...(p.seo||{}),title:x.title,description:x.description,auto_generated:true,score:x.score,generated_at:new Date().toISOString()};await a.s.rpc('set_project_seo',{p_tenant_id:a.tenantId,p_project_id:id,p_seo:payload});revalidatePath('/admin/seo')}
export async function generateAllMissingSeo(){const a=await managed(),[{data:pages},{data:projects}]=await Promise.all([a.s.from('pages').select('id,title,slug,seo').eq('tenant_id',a.tenantId),a.s.from('projects').select('id,title,slug,summary,seo').eq('tenant_id',a.tenantId)]);for(const p of pages||[]){const seo=(p.seo||{})as any;if(seo.title&&seo.description)continue;const{data:b}=await a.s.from('page_blocks').select('data').eq('tenant_id',a.tenantId).eq('page_id',p.id).eq('visible',true).order('position'),x=generateSeo({title:p.title,slug:p.slug,body:(b||[]).map((z:any)=>[z.data?.title,z.data?.text].filter(Boolean).join(' ')).join(' ')});await a.s.rpc('set_page_seo',{p_tenant_id:a.tenantId,p_page_id:p.id,p_seo:{...seo,title:x.title,description:x.description,auto_generated:true,score:x.score,generated_at:new Date().toISOString()}})}for(const p of projects||[]){const seo=(p.seo||{})as any;if(seo.title&&seo.description)continue;const x=generateSeo({title:p.title,slug:p.slug,summary:p.summary});await a.s.rpc('set_project_seo',{p_tenant_id:a.tenantId,p_project_id:p.id,p_seo:{...seo,title:x.title,description:x.description,auto_generated:true,score:x.score,generated_at:new Date().toISOString()}})}revalidatePath('/admin/seo')}
