import Link from 'next/link'
import ActionForm from '@/app/admin/components/ActionForm'
import {createClient} from '@/lib/supabase/server'
import {PERMISSIONS,requirePermission} from '@/lib/authz/permissions'
import {getAdminLocale} from '@/lib/i18n/admin-locale'
import {saveBindingAction,saveCourseAction,saveCourseTranslationAction,saveCurriculumAction,saveTopicAction,saveTranslationAction} from './actions'

type Topic={id:string;key:string;module_key:string|null;feature_key:string|null;minimum_permission:string|null;status:string;category:string;audience:string;is_featured:boolean;estimated_minutes:number;sort_order:number}
type Translation={topic_id:string;locale:string;title:string;summary:string;body_markdown:string;example_markdown:string;steps:unknown[];warnings:unknown[];search_keywords:string[];version:number}
type Course={id:string;key:string;module_key:string|null;status:string;audience:string;estimated_minutes:number;sort_order:number}
type CourseTranslation={course_id:string;locale:string;title:string;summary:string;intro_markdown:string;version:number}
const copy={
  fa:{eyebrow:'موتور راهنمای راوا',title:'مدیریت راهنما و آموزش',intro:'تمام راهنماهای فارسی را ببینید، متن اصلی را ویرایش کنید و هر آموزش را به صفحه مرتبط متصل کنید.',newTopic:'ساخت راهنمای جدید',newTopicCopy:'برای هر قابلیت یا عملیات مهم، یک شناسه پایدار و محتوای کامل بسازید.',technicalKey:'شناسه فنی راهنما',module:'بخش مرتبط',general:'عمومی',feature:'شناسه فنی قابلیت',permission:'حداقل دسترسی لازم',none:'بدون محدودیت اضافه',category:'دسته‌بندی',audience:'مخاطب',status:'وضعیت',reading:'زمان مطالعه',order:'ترتیب نمایش',featured:'برجسته',featuredCopy:'در مرکز آموزش در اولویت نمایش داده شود',saveTopic:'ذخیره راهنما',saveTopicConfirm:'این راهنما در موتور آموزش ذخیره شود؟',catalog:'فهرست راهنماهای فارسی',catalogCopy:'برای مشاهده و ویرایش متن کامل، روی عنوان راهنما کلیک کنید.',guideTitle:'عنوان راهنما',version:'نسخه',edit:'مشاهده و ویرایش',editor:'ویرایش متن کامل راهنما',selectGuide:'ابتدا یکی از عنوان‌های فهرست را انتخاب کنید.',summary:'خلاصه',body:'متن اصلی آموزش',example:'مثال کاربردی',steps:'مراحل؛ هر خط یک مرحله',warnings:'هشدارها؛ هر خط یک هشدار',keywords:'کلیدواژه‌های جست‌وجو؛ با ویرگول جدا کنید',saveTranslation:'ذخیره متن فارسی',saveTranslationConfirm:'نسخه فارسی این آموزش ذخیره شود؟',binding:'اتصال راهنما به صفحه',bindingCopy:'مسیر صفحه را ثبت کنید تا راهنما کنار همان عملیات در دسترس باشد.',topic:'راهنما',route:'مسیر صفحه مرتبط',context:'شناسه موقعیت',priority:'اولویت',saveBinding:'ذخیره اتصال',saveBindingConfirm:'این راهنما به صفحه مشخص‌شده متصل شود؟',academy:'دوره‌های آموزشی راوا',academyCopy:'راهنماهای مستقل را در قالب دوره‌های مرحله‌به‌مرحله مرتب کنید.',courseKey:'شناسه فنی دوره',duration:'زمان دوره',saveCourse:'ذخیره دوره',saveCourseConfirm:'این دوره آموزشی ذخیره شود؟',course:'دوره',courseTitle:'عنوان دوره',courseSummary:'خلاصه دوره',courseIntro:'مقدمه دوره',saveCourseText:'ذخیره متن فارسی دوره',courseTextConfirm:'نسخه فارسی دوره ذخیره شود؟',curriculum:'سرفصل‌های دوره',lessons:'درس‌ها و راهنماها',saveCurriculum:'ذخیره سرفصل',curriculumConfirm:'فهرست درس‌های این دوره جایگزین شود؟',published:'منتشرشده',draft:'پیش‌نویس',archived:'بایگانی‌شده',all:'همه',owner:'مالک',admin:'مدیر',editorRole:'ویرایشگر',staff:'همکار',customer:'مشتری'},
  en:{eyebrow:'RAVA guidance engine',title:'Help and learning management',intro:'Review every English guide, edit its complete content, and connect it to the relevant page.',newTopic:'Create a guide',newTopicCopy:'Create a stable identifier and complete content for every important feature or operation.',technicalKey:'Technical guide identifier',module:'Related module',general:'General',feature:'Technical feature identifier',permission:'Minimum permission',none:'No additional restriction',category:'Category',audience:'Audience',status:'Status',reading:'Reading time',order:'Display order',featured:'Featured',featuredCopy:'Prioritize this guide in the learning center',saveTopic:'Save guide',saveTopicConfirm:'Save this guide in the learning engine?',catalog:'English help catalog',catalogCopy:'Select a guide title to review and edit its complete content.',guideTitle:'Guide title',version:'Version',edit:'Review and edit',editor:'Edit the complete guide',selectGuide:'Select a title from the catalog first.',summary:'Summary',body:'Main learning content',example:'Practical example',steps:'Steps; one step per line',warnings:'Warnings; one warning per line',keywords:'Search keywords; separate with commas',saveTranslation:'Save English content',saveTranslationConfirm:'Save the English version of this guide?',binding:'Connect help to a page',bindingCopy:'Save the page route so guidance appears beside the relevant operation.',topic:'Guide',route:'Related page route',context:'Context identifier',priority:'Priority',saveBinding:'Save connection',saveBindingConfirm:'Connect this guide to the specified page?',academy:'RAVA learning courses',academyCopy:'Arrange individual guides into structured, step-by-step courses.',courseKey:'Technical course identifier',duration:'Course duration',saveCourse:'Save course',saveCourseConfirm:'Save this learning course?',course:'Course',courseTitle:'Course title',courseSummary:'Course summary',courseIntro:'Course introduction',saveCourseText:'Save English course content',courseTextConfirm:'Save the English version of this course?',curriculum:'Course curriculum',lessons:'Lessons and guides',saveCurriculum:'Save curriculum',curriculumConfirm:'Replace this course curriculum?',published:'Published',draft:'Draft',archived:'Archived',all:'Everyone',owner:'Owner',admin:'Administrator',editorRole:'Editor',staff:'Staff',customer:'Customer'},
}
const lines=(value:unknown)=>Array.isArray(value)?value.map(String).join('\n'):''

export default async function HelpManagementPage({searchParams}:{searchParams:Promise<{topic?:string}>}){
  await requirePermission(PERMISSIONS.PLATFORM_HELP_MANAGE)
  const locale=await getAdminLocale(),t=copy[locale],params=await searchParams,supabase=await createClient()
  const [topicsR,translationsR,coursesR,courseTranslationsR,modulesR,permissionsR,bindingsR,curriculumR]=await Promise.all([
    supabase.from('help_topics').select('id,key,module_key,feature_key,minimum_permission,status,category,audience,is_featured,estimated_minutes,sort_order').order('sort_order').order('key'),
    supabase.from('help_translations').select('topic_id,locale,title,summary,body_markdown,example_markdown,steps,warnings,search_keywords,version').eq('locale',locale).order('title'),
    supabase.from('academy_courses').select('id,key,module_key,status,audience,estimated_minutes,sort_order').order('sort_order').order('key'),
    supabase.from('academy_course_translations').select('course_id,locale,title,summary,intro_markdown,version').eq('locale',locale).order('title'),
    supabase.from('module_catalog').select('key,name_fa,name_en').order('key'),
    supabase.from('permissions').select('key,name_fa,name_en').order('key'),
    supabase.from('help_context_bindings').select('id,topic_id,route_pattern,context_key,priority').order('priority'),
    supabase.from('academy_course_topics').select('course_id,topic_id,position').order('position'),
  ])
  const topics=(topicsR.data??[]) as Topic[],translations=(translationsR.data??[]) as Translation[],courses=(coursesR.data??[]) as Course[],courseTranslations=(courseTranslationsR.data??[]) as CourseTranslation[]
  const modules=modulesR.data??[],permissions=permissionsR.data??[],bindings=bindingsR.data??[],curriculum=curriculumR.data??[]
  const title=(id:string)=>translations.find(item=>item.topic_id===id)?.title??(locale==='fa'?'راهنمای بدون عنوان':'Untitled guide')
  const selectedTopic=topics.find(item=>item.id===params.topic),selectedTranslation=selectedTopic?translations.find(item=>item.topic_id===selectedTopic.id):undefined
  const audience=[['all',t.all],['owner',t.owner],['admin',t.admin],['editor',t.editorRole],['staff',t.staff],['customer',t.customer]],statuses=[['draft',t.draft],['published',t.published],['archived',t.archived]]
  return <main className="admin-shell"><header className="admin-head"><div><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p></div></header>
    <section className="admin-panel"><div className="admin-section-title"><div><h2>{t.catalog}</h2><p>{t.catalogCopy}</p></div><span>{topics.length}</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>{t.guideTitle}</th><th>{t.status}</th><th>{t.version}</th><th>{t.edit}</th></tr></thead><tbody>{topics.map(topic=>{const translation=translations.find(item=>item.topic_id===topic.id);return <tr key={topic.id}><td><Link className="rava-help-table-link" href={`/admin/help?topic=${topic.id}#guide-editor`}>{translation?.title??(locale==='fa'?'بدون عنوان':'Untitled')}</Link></td><td>{statuses.find(item=>item[0]===topic.status)?.[1]??(locale==='fa'?'نامشخص':'Unknown')}</td><td>{translation?.version??'—'}</td><td><Link className="admin-muted-button" href={`/admin/help?topic=${topic.id}#guide-editor`}>{t.edit}</Link></td></tr>})}</tbody></table></div></section>
    <section className="admin-panel" id="guide-editor"><div className="admin-section-title"><div><h2>{t.editor}</h2><p>{selectedTopic?title(selectedTopic.id):t.selectGuide}</p></div></div>{selectedTopic?<ActionForm key={`${selectedTopic.id}-${locale}`} action={saveTranslationAction} className="admin-form" confirmTitle={t.saveTranslation} confirmMessage={t.saveTranslationConfirm}><input type="hidden" name="topic_id" value={selectedTopic.id}/><input type="hidden" name="locale" value={locale}/><label>{t.guideTitle}<input name="title" required defaultValue={selectedTranslation?.title??''}/></label><label>{t.summary}<textarea name="summary" rows={3} defaultValue={selectedTranslation?.summary??''}/></label><label className="admin-full-field">{t.body}<textarea name="body_markdown" rows={10} defaultValue={selectedTranslation?.body_markdown??''}/></label><label className="admin-full-field">{t.example}<textarea name="example_markdown" rows={5} defaultValue={selectedTranslation?.example_markdown??''}/></label><label>{t.steps}<textarea name="steps" rows={7} defaultValue={lines(selectedTranslation?.steps)}/></label><label>{t.warnings}<textarea name="warnings" rows={7} defaultValue={lines(selectedTranslation?.warnings)}/></label><label className="admin-full-field">{t.keywords}<input name="keywords" defaultValue={(selectedTranslation?.search_keywords??[]).join(', ')}/></label><button className="admin-primary-button" type="submit">{t.saveTranslation}</button></ActionForm>:<div className="admin-empty">{t.selectGuide}</div>}</section>
    <details className="admin-panel rava-admin-advanced"><summary>{t.newTopic}</summary><p>{t.newTopicCopy}</p><ActionForm action={saveTopicAction} className="admin-form" confirmTitle={t.saveTopic} confirmMessage={t.saveTopicConfirm}><label>{t.technicalKey}<input name="key" required dir="ltr"/></label><label>{t.module}<select name="module_key" defaultValue=""><option value="">{t.general}</option>{modules.map(module=><option key={module.key} value={module.key}>{locale==='fa'?module.name_fa:module.name_en}</option>)}</select></label><label>{t.feature}<input name="feature_key" dir="ltr"/></label><label>{t.permission}<select name="minimum_permission" defaultValue=""><option value="">{t.none}</option>{permissions.map(permission=><option key={permission.key} value={permission.key}>{locale==='fa'?permission.name_fa:permission.name_en}</option>)}</select></label><label>{t.category}<input name="category" defaultValue="general" dir="ltr"/></label><label>{t.audience}<select name="audience" defaultValue="all">{audience.map(item=><option key={item[0]} value={item[0]}>{item[1]}</option>)}</select></label><label>{t.status}<select name="status" defaultValue="draft">{statuses.map(item=><option key={item[0]} value={item[0]}>{item[1]}</option>)}</select></label><label>{t.reading}<input type="number" name="estimated_minutes" min="1" max="240" defaultValue="3"/></label><label>{t.order}<input type="number" name="sort_order" defaultValue="0"/></label><label className="admin-check"><input type="checkbox" name="featured"/><span><b>{t.featured}</b><small>{t.featuredCopy}</small></span></label><button className="admin-primary-button" type="submit">{t.saveTopic}</button></ActionForm></details>
    <details className="admin-panel rava-admin-advanced"><summary>{t.binding}</summary><p>{t.bindingCopy}</p><ActionForm action={saveBindingAction} className="admin-form" confirmTitle={t.saveBinding} confirmMessage={t.saveBindingConfirm}><label>{t.topic}<select name="topic_id" required defaultValue=""><option value="" disabled>{t.topic}</option>{topics.map(topic=><option key={topic.id} value={topic.id}>{title(topic.id)}</option>)}</select></label><label>{t.route}<input name="route_pattern" dir="ltr" required/></label><label>{t.context}<input name="context_key" dir="ltr"/></label><label>{t.priority}<input name="priority" type="number" defaultValue="100"/></label><button className="admin-primary-button" type="submit">{t.saveBinding}</button></ActionForm><small>{bindings.length}</small></details>
    <details className="admin-panel rava-admin-advanced"><summary>{t.academy}</summary><p>{t.academyCopy}</p><ActionForm action={saveCourseAction} className="admin-form" confirmTitle={t.saveCourse} confirmMessage={t.saveCourseConfirm}><label>{t.courseKey}<input name="key" required dir="ltr"/></label><label>{t.module}<select name="module_key" defaultValue=""><option value="">{t.general}</option>{modules.map(module=><option key={module.key} value={module.key}>{locale==='fa'?module.name_fa:module.name_en}</option>)}</select></label><label>{t.status}<select name="status" defaultValue="draft">{statuses.map(item=><option key={item[0]} value={item[0]}>{item[1]}</option>)}</select></label><label>{t.audience}<select name="audience" defaultValue="all">{audience.map(item=><option key={item[0]} value={item[0]}>{item[1]}</option>)}</select></label><label>{t.duration}<input name="estimated_minutes" type="number" defaultValue="15"/></label><label>{t.order}<input name="sort_order" type="number" defaultValue="0"/></label><button className="admin-primary-button" type="submit">{t.saveCourse}</button></ActionForm><ActionForm action={saveCourseTranslationAction} className="admin-form" confirmTitle={t.saveCourseText} confirmMessage={t.courseTextConfirm}><label>{t.course}<select name="course_id" required defaultValue=""><option value="" disabled>{t.course}</option>{courses.map(course=><option key={course.id} value={course.id}>{courseTranslations.find(item=>item.course_id===course.id)?.title??(locale==='fa'?'دوره بدون عنوان':'Untitled course')}</option>)}</select></label><input type="hidden" name="locale" value={locale}/><label>{t.courseTitle}<input name="title" required/></label><label>{t.courseSummary}<textarea name="summary" rows={2}/></label><label className="admin-full-field">{t.courseIntro}<textarea name="intro_markdown" rows={5}/></label><button className="admin-primary-button" type="submit">{t.saveCourseText}</button></ActionForm><ActionForm action={saveCurriculumAction} confirmTitle={t.saveCurriculum} confirmMessage={t.curriculumConfirm}><label>{t.course}<select name="course_id" required defaultValue=""><option value="" disabled>{t.course}</option>{courses.map(course=><option key={course.id} value={course.id}>{courseTranslations.find(item=>item.course_id===course.id)?.title??(locale==='fa'?'دوره بدون عنوان':'Untitled course')}</option>)}</select></label><fieldset className="admin-permission-grid"><legend>{t.lessons}</legend>{topics.filter(topic=>topic.status==='published').map(topic=><label className="admin-check" key={topic.id}><input type="checkbox" name="topic_ids" value={topic.id}/><span><b>{title(topic.id)}</b></span></label>)}</fieldset><button className="admin-primary-button" type="submit">{t.saveCurriculum}</button></ActionForm><small>{curriculum.length}</small></details>
  </main>
}
