'use server'
import {revalidatePath} from 'next/cache';import type{AdminActionState}from '@/app/admin/components/ActionForm';import{logEvent}from '@/lib/observability/logger';import{getTenantContext}from '@/lib/platform/tenant-context'
const SLUG=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;const STATUSES=['draft','published','hidden','scheduled']
async function staff(){const a=await getTenantContext();if(!['super_admin','admin','content_manager'].includes(a.profile.role)&&!a.isPlatform)throw new Error('forbidden');return a}
function parseGallery(raw:string){try{const x=JSON.parse(raw||'[]');if(!Array.isArray(x)||x.length>60)return null;const out=[]as any[];for(const item of x){const media_id=String(item?.media_id||''),kind=String(item?.kind||''),caption=String(item?.caption||'').trim();if(!/^[0-9a-f-]{36}$/i.test(media_id)||!['image','video'].includes(kind)||caption.length>1200)return null;out.push({media_id,kind,caption})}return out}catch{return null}}
function parse(f:FormData){const title=String(f.get('title')||'').trim(),slug=String(f.get('slug')||'').trim().toLowerCase(),status=String(f.get('status')||'draft'),summary=String(f.get('summary')||'').trim(),category=String(f.get('category')||'general').trim().toLowerCase(),client=String(f.get('client_name')||'').trim(),services=String(f.get('services')||'').split('\n').map(x=>x.trim()).filter(Boolean).slice(0,30),cover=String(f.get('cover_media_id')||'').trim()||null,gallery=parseGallery(String(f.get('gallery_items')||'[]')),featured=String(f.get('featured'))==='on',projectDate=String(f.get('project_date')||'')||null,scheduledAt=String(f.get('scheduled_at')||'')||null,seoTitle=String(f.get('seo_title')||'').trim(),seoDescription=String(f.get('seo_description')||'').trim();if(gallery===null||title.length<2||title.length>180||!SLUG.test(slug)||!STATUSES.includes(status)||summary.length>1200||category.length<2||category.length>80||client.length>180||seoTitle.length>180||seoDescription.length>500)return null;if(status==='scheduled'&&!scheduledAt)return null;return{title,slug,status,summary:summary||null,category,client_name:client||null,services,cover_media_id:cover,gallery_media_ids:gallery.filter((x:any)=>x.kind==='image').map((x:any)=>x.media_id),gallery_items:gallery,featured,project_date:projectDate,scheduled_at:status==='scheduled'?new Date(scheduledAt).toISOString():null,seo:{title:seoTitle,description:seoDescription}}}
export async function createProject(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await staff(),p=parse(f);if(!p)return{ok:false,message:'اطلاعات پروژه معتبر نیست.',nonce:Date.now()};const{data,error}=await a.s.from('projects').insert({...p,tenant_id:a.tenantId,created_by:a.userId,updated_by:a.userId}).select('id').single();if(error){const eid=await logEvent({category:'error',eventName:'projects.create.failed',actorUserId:a.userId,actorRole:a.profile.role,error,metadata:{tenant_id:a.tenantId}});return{ok:false,message:`ساخت پروژه انجام نشد. کد خطا: ${eid}`,nonce:Date.now()}}return{ok:true,message:'پروژه با موفقیت ساخته شد.',redirectTo:`/admin/projects/${data.id}`,nonce:Date.now()}}
export async function updateProject(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await staff(),id=String(f.get('id')||''),p=parse(f);if(!id||!p)return{ok:false,message:'اطلاعات پروژه معتبر نیست.',nonce:Date.now()};const{error}=await a.s.from('projects').update({...p,updated_by:a.userId,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',a.tenantId);if(error){const eid=await logEvent({category:'error',eventName:'projects.update.failed',actorUserId:a.userId,actorRole:a.profile.role,error,metadata:{project_id:id,tenant_id:a.tenantId}});return{ok:false,message:`ویرایش انجام نشد. کد خطا: ${eid}`,nonce:Date.now()}}revalidatePath('/admin/projects');revalidatePath(`/admin/projects/${id}`);return{ok:true,message:'تغییرات پروژه ذخیره شد.',nonce:Date.now()}}
export async function deleteProject(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await staff(),id=String(f.get('id')||'');if(!id)return{ok:false,message:'شناسه پروژه معتبر نیست.',nonce:Date.now()};const{error}=await a.s.from('projects').delete().eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:'حذف پروژه انجام نشد.',nonce:Date.now()};revalidatePath('/admin/projects');return{ok:true,message:'پروژه حذف شد.',redirectTo:'/admin/projects',nonce:Date.now()}}
