'use client'
import { useEffect,useMemo,useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Asset={id:string;storage_path:string;file_name:string;alt_text:string;title:string;folder:string;mime_type:string}
const SIZE=18
export default function ProjectMediaPicker({name,multiple=false,defaultValue=[]}:{name:string;multiple?:boolean;defaultValue?:string[]}){
 const s=useMemo(()=>createClient(),[]),[open,setOpen]=useState(false),[assets,setAssets]=useState<Asset[]>([]),[selected,setSelected]=useState<string[]>(defaultValue),[selectedAssets,setSelectedAssets]=useState<Asset[]>([]),[q,setQ]=useState(''),[folder,setFolder]=useState('projects'),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false)
 const pages=Math.max(1,Math.ceil(total/SIZE));const url=(p:string)=>s.storage.from('rava-media').getPublicUrl(p).data.publicUrl
 async function load(p=1){setLoading(true);let query=s.from('media_assets').select('id,storage_path,file_name,alt_text,title,folder,mime_type',{count:'exact'}).is('deleted_at',null).order('created_at',{ascending:false});const clean=q.trim().replace(/[%_,()]/g,' ');if(clean)query=query.or(`file_name.ilike.%${clean}%,title.ilike.%${clean}%,alt_text.ilike.%${clean}%`);if(folder!=='all')query=query.eq('folder',folder);const from=(p-1)*SIZE,{data,count}=await query.range(from,from+SIZE-1);setAssets((data||[]) as Asset[]);setTotal(count||0);setPage(p);setLoading(false)}
 useEffect(()=>{if(!defaultValue.length)return; s.from('media_assets').select('id,storage_path,file_name,alt_text,title,folder,mime_type').in('id',defaultValue).then(({data})=>setSelectedAssets((data||[]) as Asset[]))},[])
 function toggle(a:Asset){if(multiple){setSelected(v=>v.includes(a.id)?v.filter(x=>x!==a.id):[...v,a.id].slice(0,60));setSelectedAssets(v=>v.some(x=>x.id===a.id)?v.filter(x=>x.id!==a.id):[...v,a].slice(0,60))}else{setSelected([a.id]);setSelectedAssets([a]);setOpen(false)}}
 function remove(id:string){setSelected(v=>v.filter(x=>x!==id));setSelectedAssets(v=>v.filter(x=>x.id!==id))}
 function move(id:string,dir:-1|1){const i=selected.indexOf(id),j=i+dir;if(i<0||j<0||j>=selected.length)return;const next=[...selected];[next[i],next[j]]=[next[j],next[i]];setSelected(next);setSelectedAssets(next.map(x=>selectedAssets.find(a=>a.id===x)!).filter(Boolean))}
 return <div className="admin-media-picker"><input type="hidden" name={name} value={multiple?selected.join(','):(selected[0]||'')}/><div className="admin-media-grid">{selectedAssets.map((a,i)=><article className="admin-media-card" key={a.id}><img src={url(a.storage_path)} alt={a.alt_text||a.file_name}/><div className="admin-media-meta"><b>{a.title||a.file_name}</b><small>{multiple?`ترتیب ${i+1}`:'کاور پروژه'}</small></div><div className="admin-media-actions">{multiple?<><button type="button" className="admin-muted-button" onClick={()=>move(a.id,-1)}>↑</button><button type="button" className="admin-muted-button" onClick={()=>move(a.id,1)}>↓</button></>:null}<button type="button" className="admin-danger-button" onClick={()=>remove(a.id)}>حذف</button></div></article>)}</div><button type="button" className="admin-muted-button" onClick={()=>{setOpen(true);load(1)}}>{multiple?'انتخاب تصاویر گالری':'انتخاب تصویر کاور'}</button>{open?<div className="admin-modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="admin-modal admin-media-modal" onMouseDown={e=>e.stopPropagation()}><div className="admin-section-title"><div><h3>{multiple?'انتخاب چند تصویر':'انتخاب کاور'}</h3><p>جستجو، پوشه‌بندی، صفحه‌بندی و انتخاب بصری از Media Library.</p></div><span>{total.toLocaleString('fa-IR')} فایل</span></div><div className="admin-media-picker-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو…"/><select value={folder} onChange={e=>setFolder(e.target.value)}><option value="all">همه پوشه‌ها</option><option value="projects">projects</option><option value="general">general</option><option value="hero">hero</option><option value="branding">branding</option></select><button type="button" className="admin-primary-button" onClick={()=>load(1)}>اعمال</button></div>{loading?<div className="admin-empty">در حال بارگذاری…</div>:<div className="admin-media-grid admin-media-picker-grid">{assets.map(a=>{const on=selected.includes(a.id);return <article key={a.id} className={`admin-media-card ${on?'is-selected':''}`}><img src={url(a.storage_path)} alt={a.alt_text||a.file_name}/><div className="admin-media-meta"><b>{a.title||a.file_name}</b><small>{a.folder}</small></div><button type="button" className={on?'admin-muted-button':'admin-primary-button'} onClick={()=>toggle(a)}>{on?'حذف از انتخاب':'انتخاب'}</button></article>})}</div>}<div className="admin-pagination"><button type="button" className="admin-muted-button" disabled={page<=1} onClick={()=>load(page-1)}>قبل</button><span>{page} / {pages}</span><button type="button" className="admin-muted-button" disabled={page>=pages} onClick={()=>load(page+1)}>بعد</button></div><div className="admin-modal-actions"><button type="button" className="admin-primary-button" onClick={()=>setOpen(false)}>تأیید انتخاب‌ها</button></div></div></div>:null}</div>
}
