import Link from'next/link';import{createClient}from'@/lib/supabase/server';import{getPublicTenant}from'@/lib/platform/public-tenant';export const revalidate=300
const services=[
 ['01','استراتژی و هویت برند','از جایگاه‌سازی و لحن برند تا ساخت هویتی که قابل تشخیص و قابل توسعه باشد.'],
 ['02','طراحی و توسعه وب','سایت‌های سریع، ماژولار و قابل مدیریت؛ از پورتفولیو و خدمات تا فروشگاه و Commerce.'],
 ['03','تولید محتوا','عکس، ویدیو، کمپین و محتوایی که فقط زیبا نیست؛ برای دیده‌شدن و تبدیل‌شدن طراحی می‌شود.'],
 ['04','هوش مصنوعی و اتوماسیون','استفاده کاربردی از AI در تولید، سئو، تحلیل و فرایندهای روزمره کسب‌وکار.'],
 ['05','سئو و رشد','سئوی فنی، محتوایی و تحلیلی با تصمیم‌گیری مبتنی بر داده و گزارش شفاف.'],
 ['06','طراحی سیستم برند','ساخت زبان بصری یکپارچه برای وب، شبکه‌های اجتماعی، کمپین و نقاط تماس برند.']
]
function publicUrl(path:string){const base=process.env.NEXT_PUBLIC_SUPABASE_URL;return base?`${base}/storage/v1/object/public/rava-media/${path}`:''}
export default async function HomePage(){const tenant=await getPublicTenant(),s=await createClient();let projects:any[]=[];let byId=new Map<string,any>();if(tenant){const{data}=await s.from('projects').select('id,title,slug,summary,category,featured,cover_media_id').eq('tenant_id',tenant.id).eq('status','published').order('featured',{ascending:false}).order('published_at',{ascending:false}).limit(4);projects=data||[];const ids=projects.map(p=>p.cover_media_id).filter(Boolean);if(ids.length){const{data:media}=await s.from('media_assets').select('id,storage_path,alt_text,title').eq('tenant_id',tenant.id).in('id',ids);byId=new Map((media||[]).map((m:any)=>[m.id,m]))}}return <main className="rava-home">
<header className="site-header"><div className="container nav-shell"><a className="brand" href="#top">RAVA <b>TEAM</b></a><nav className="desktop-nav" aria-label="منوی اصلی"><a href="#services">خدمات</a><a href="#works">پروژه‌ها</a><a href="#about">درباره راوا</a><a href="#contact">تماس</a></nav><a className="button small" href="#contact">شروع همکاری <span>↗</span></a></div></header>
<section className="rava-hero" id="top"><div className="container rava-hero-grid"><div className="rava-hero-copy"><span className="rava-eyebrow">STRATEGY · DESIGN · CONTENT · TECHNOLOGY</span><h1>RAVA <span>TEAM</span></h1><p className="rava-hero-lead">ما برای برندها فقط محتوا یا سایت نمی‌سازیم. از استراتژی تا طراحی، تکنولوژی و رشد، یک تجربه منسجم می‌سازیم که دیده شود، به خاطر بماند و نتیجه بدهد.</p><div className="rava-hero-actions"><a className="button" href="#works">دیدن پروژه‌ها <span>↗</span></a><a className="button ghost" href="#services">خدمات راوا</a></div></div><div className="rava-hero-art" aria-label="RAVA visual identity canvas"><div className="rava-orbit"/><div className="rava-hero-meta"><div><strong>RAVA / 01</strong><br/>CREATIVE BUSINESS SYSTEM</div><div>SHIRAZ · IR<br/>AVAILABLE FOR SELECTED PROJECTS</div></div></div></div></section>
<div className="rava-marquee" aria-hidden="true"><div className="rava-marquee-track"><span>BRAND STRATEGY</span><b>✦</b><span>WEB DESIGN</span><b>✦</b><span>CONTENT PRODUCTION</span><b>✦</b><span>AI WORKFLOWS</span><b>✦</b><span>SEO & GROWTH</span><b>✦</b><span>BRAND STRATEGY</span><b>✦</b><span>WEB DESIGN</span><b>✦</b><span>CONTENT PRODUCTION</span><b>✦</b><span>AI WORKFLOWS</span><b>✦</b><span>SEO & GROWTH</span><b>✦</b></div></div>
<section className="rava-section" id="services"><div className="container"><div className="rava-section-head"><span className="rava-section-index">01 / SERVICES</span><h2>برای ساختن یک برند جدی، تکه‌های پراکنده کافی نیست.</h2></div><div className="rava-services">{services.map(([n,title,desc])=><article className="rava-service" key={n}><span className="rava-service-num">{n}</span><div><h3>{title}</h3><p>{desc}</p></div></article>)}</div></div></section>
<section className="rava-section" id="works"><div className="container"><div className="rava-section-head"><span className="rava-section-index">02 / SELECTED WORK</span><h2>کارهایی که قرار نیست شبیه بقیه باشند.</h2></div><div className="rava-work-grid">{projects.length?projects.map((p:any,index:number)=>{const m=byId.get(p.cover_media_id);return <Link className="rava-work" href={`/projects/${p.slug}`} key={p.id}><div className="rava-work-media">{m?.storage_path?<img src={publicUrl(m.storage_path)} alt={m.alt_text||m.title||p.title} loading={index<2?'eager':'lazy'}/>:null}</div><div className="rava-work-shade"/><span className="rava-work-arrow">↖</span><div className="rava-work-body"><span>{p.category||'PROJECT'}{p.featured?' · FEATURED':''}</span><h3>{p.title}</h3></div></Link>}):[0,1,2,3].map((x,i)=><article className="rava-work" key={x}><div className="rava-work-media"/><div className="rava-work-shade"/><span className="rava-work-arrow">↖</span><div className="rava-work-body"><span>CASE STUDY · {String(i+1).padStart(2,'0')}</span><h3>{['Brand Direction','Digital Experience','Content System','Creative Campaign'][i]}</h3></div></article>)}</div><div className="rava-hero-actions" style={{marginTop:28}}><Link className="button ghost" href="/projects">همه پروژه‌ها <span>↗</span></Link></div></div></section>
<section className="rava-section" id="about"><div className="container"><div className="rava-section-head"><span className="rava-section-index">03 / ABOUT RAVA</span><h2>راوا جایی بین خلاقیت، کسب‌وکار و تکنولوژی ایستاده.</h2></div><div className="rava-about"><p className="rava-about-big">هدف ما ساخت خروجی‌های زیبا نیست؛ ساختن سیستم‌هایی است که برند را حرفه‌ای‌تر، سریع‌تر و قابل رشدتر می‌کنند.</p><div className="rava-about-side"><strong>BUILT TO EVOLVE.</strong><p>هر پروژه را طوری طراحی می‌کنیم که با رشد کسب‌وکار بن‌بست نسازد؛ از هویت و محتوا تا وب، سئو و اتوماسیون.</p><div className="rava-founder"><span>FOUNDER / CREATIVE LEAD</span><b>MOHAMMAD GHASEMI</b></div></div></div></div></section>
<section className="rava-section" id="contact"><div className="container"><div className="rava-cta"><span className="rava-eyebrow">START SOMETHING WORTH SEEING</span><h2>اگر قرار است انجامش بدهیم، درست انجامش می‌دهیم.</h2><div className="rava-cta-row"><p>برای همکاری، طراحی سایت، تولید محتوا، سئو یا ساخت یک سیستم اختصاصی برای برندت با راوا در تماس باش.</p><a className="button" href="mailto:hello@ravateam.ir">شروع گفتگو <span>↗</span></a></div></div></div></section>
<footer className="rava-footer"><div className="container rava-footer-row"><span className="rava-footer-brand">RAVA TEAM</span><span>CREATIVE · DIGITAL · TECHNOLOGY</span><span>© 2026 RAVA TEAM</span></div></footer>
</main>}
