import Link from'next/link';import{createClient}from'@/lib/supabase/server';import{getPublicTenant}from'@/lib/platform/public-tenant';import{DEFAULT_HOME_CONTENT,normalizeHomeContent}from'@/lib/cms/home-content';export const revalidate=300
const nav=[['#services','خدمات'],['#works','پروژه‌ها'],['#about','درباره راوا'],['#contact','تماس']]
function publicUrl(path:string){const base=process.env.NEXT_PUBLIC_SUPABASE_URL;return base?`${base}/storage/v1/object/public/rava-media/${path}`:''}
export default async function HomePage(){const tenant=await getPublicTenant(),s=await createClient();let projects:any[]=[];let byId=new Map<string,any>(),content=DEFAULT_HOME_CONTENT;if(tenant){const[{data:home},{data:projectRows}]=await Promise.all([s.from('home_content_settings').select('published').eq('tenant_id',tenant.id).maybeSingle(),s.from('projects').select('id,title,slug,summary,category,featured,cover_media_id').eq('tenant_id',tenant.id).eq('status','published').order('featured',{ascending:false}).order('published_at',{ascending:false}).limit(4)]);content=normalizeHomeContent(home?.published||DEFAULT_HOME_CONTENT);projects=projectRows||[];const ids=projects.map(p=>p.cover_media_id).filter(Boolean);if(ids.length){const{data:media}=await s.from('media_assets').select('id,storage_path,alt_text,title').eq('tenant_id',tenant.id).in('id',ids);byId=new Map((media||[]).map((m:any)=>[m.id,m]))}}return <main className="rava-home">
<header className="site-header"><div className="container nav-shell"><a className="brand" href="#top">{content.brandLine1} <b>{content.brandLine2}</b></a><nav className="desktop-nav" aria-label="منوی اصلی">{nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav><a className="button small desktop-start" href="#contact">شروع همکاری <span>↗</span></a><details className="rava-mobile-menu"><summary aria-label="باز کردن منوی سایت"><span/><span/></summary><div className="rava-mobile-panel">{nav.map(([href,label],i)=><a key={href} href={href}><small>0{i+1}</small>{label}</a>)}<a className="button" href="#contact">شروع همکاری <span>↗</span></a></div></details></div></header>
<section className="rava-hero" id="top"><div className="container rava-hero-grid"><div className="rava-hero-copy"><span className="rava-eyebrow">{content.eyebrow}</span><h1>{content.brandLine1} <span>{content.brandLine2}</span></h1><p className="rava-hero-lead">{content.heroLead}</p><div className="rava-hero-actions"><a className="button" href={content.primaryCtaHref}>{content.primaryCtaLabel} <span>↗</span></a><a className="button ghost" href={content.secondaryCtaHref}>{content.secondaryCtaLabel}</a></div></div><div className="rava-hero-art" aria-label="RAVA visual identity canvas"><div className="rava-orbit"/><div className="rava-hero-meta"><div><strong>RAVA / 01</strong><br/>CREATIVE BUSINESS SYSTEM</div><div>{content.location.toUpperCase()}<br/>AVAILABLE FOR SELECTED PROJECTS</div></div></div></div></section>
<div className="rava-marquee" aria-hidden="true"><div className="rava-marquee-track">{[...content.services,...content.services].map((x,i)=><span key={i}>{x.title}</span>)}</div></div>
<section className="rava-section" id="services"><div className="container"><div className="rava-section-head"><span className="rava-section-index">01 / SERVICES</span><h2>{content.servicesTitle}</h2></div><div className="rava-services">{content.services.map((x,i)=><article className="rava-service" key={`${x.title}-${i}`}><span className="rava-service-num">{String(i+1).padStart(2,'0')}</span><div><h3>{x.title}</h3><p>{x.description}</p></div></article>)}</div></div></section>
<section className="rava-section" id="works"><div className="container"><div className="rava-section-head"><span className="rava-section-index">02 / SELECTED WORK</span><h2>{content.workTitle}</h2></div><div className="rava-work-grid">{projects.length?projects.map((p:any,index:number)=>{const m=byId.get(p.cover_media_id);return <Link className="rava-work" href={`/projects/${p.slug}`} key={p.id}><div className="rava-work-media">{m?.storage_path?<img src={publicUrl(m.storage_path)} alt={m.alt_text||m.title||p.title} loading={index<2?'eager':'lazy'}/>:null}</div><div className="rava-work-shade"/><span className="rava-work-arrow">↖</span><div className="rava-work-body"><span>{p.category||'PROJECT'}{p.featured?' · FEATURED':''}</span><h3>{p.title}</h3></div></Link>}):[0,1,2,3].map((x,i)=><article className="rava-work" key={x}><div className="rava-work-media"/><div className="rava-work-shade"/><span className="rava-work-arrow">↖</span><div className="rava-work-body"><span>CASE STUDY · {String(i+1).padStart(2,'0')}</span><h3>{['Brand Direction','Digital Experience','Content System','Creative Campaign'][i]}</h3></div></article>)}</div><div className="rava-hero-actions" style={{marginTop:28}}><Link className="button ghost" href="/projects">همه پروژه‌ها <span>↗</span></Link></div></div></section>
<section className="rava-section" id="about"><div className="container"><div className="rava-section-head"><span className="rava-section-index">03 / ABOUT RAVA</span><h2>{content.aboutTitle}</h2></div><div className="rava-about"><p className="rava-about-big">{content.aboutLead}</p><div className="rava-about-side"><strong>BUILT TO EVOLVE.</strong><p>{content.aboutBody}</p><div className="rava-founder"><span>{content.founderLabel}</span><b>{content.founderName}</b></div></div></div></div></section>
<section className="rava-section" id="contact"><div className="container"><div className="rava-cta"><span className="rava-eyebrow">{content.ctaEyebrow}</span><h2>{content.ctaTitle}</h2><div className="rava-cta-row"><p>{content.ctaBody}</p><a className="button" href={content.ctaHref}>{content.ctaLabel} <span>↗</span></a></div></div></div></section>
<footer className="rava-footer"><div className="container"><div className="rava-footer-meta"><div><span className="rava-footer-label">CONTACT</span><a href={`mailto:${content.contactEmail}`}>{content.contactEmail}</a><span>{content.location}</span></div><div><span className="rava-footer-label">BUSINESS INFO</span><span>{content.businessInfo}</span></div><div><span className="rava-footer-label">SOCIAL / LINKS</span><span>{content.socialLinks}</span></div></div><div className="rava-footer-row"><span className="rava-footer-brand">{content.brandLine1} {content.brandLine2}</span><span>{content.footerTagline}</span><span>© 2026 {content.brandLine1} {content.brandLine2}</span></div></div></footer>
</main>}
