'use server'
import{revalidatePath}from'next/cache';import{getTenantContext}from'@/lib/platform/tenant-context'
export type AdminActionState={ok?:boolean;message?:string;redirectTo?:string;nonce?:number}
async function editor(){const a=await getTenantContext();if(!['super_admin','admin','content_manager'].includes(a.profile.role)&&!a.isPlatform)throw new Error('forbidden');return a}
function slug(v:string){return v.trim().toLowerCase().replace(/^\/+|\/+$/g,'').replace(/\s+/g,'-').replace(/[^a-z0-9\u0600-\u06ff-]/g,'')}
function err(e:{code?:string;message?:string}|null,f:string){if(e?.code==='23505')return'این آدرس در همین سایت قبلاً استفاده شده است.';return e?.message?`خطای سرور: ${e.message}`:f}
export async function createPage(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),title=String(f.get('title')||'').trim(),s=slug(String(f.get('slug')||''));if(!title||!s)return{ok:false,message:'عنوان و آدرس صفحه الزامی است.',nonce:Date.now()};const{data,error}=await a.s.from('pages').insert({tenant_id:a.tenantId,title,slug:s,status:'draft',created_by:a.userId,updated_by:a.userId}).select('id').single();if(error||!data)return{ok:false,message:err(error,'ساخت صفحه انجام نشد.'),nonce:Date.now()};revalidatePath('/admin/pages');return{ok:true,message:`صفحه «${title}» ساخته شد.`,redirectTo:`/admin/pages/${data.id}`,nonce:Date.now()}}
export async function updatePage(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||''),title=String(f.get('title')||'').trim(),s=slug(String(f.get('slug')||'')),status=String(f.get('status')||'draft'),seoTitle=String(f.get('seo_title')||'').trim(),seoDescription=String(f.get('seo_description')||'').trim();if(!id||!title||!s||!['draft','published','hidden','scheduled'].includes(status))return{ok:false,message:'اطلاعات فرم معتبر نیست.',nonce:Date.now()};const{error}=await a.s.from('pages').update({title,slug:s,status,seo:{title:seoTitle,description:seoDescription},published_at:status==='published'?new Date().toISOString():null,updated_by:a.userId,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:err(error,'ویرایش صفحه انجام نشد.'),nonce:Date.now()};revalidatePath('/admin/pages');revalidatePath(`/admin/pages/${id}`);return{ok:true,message:`تغییرات صفحه «${title}» ذخیره شد.`,nonce:Date.now()}}
export async function setPageStatus(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||''),status=String(f.get('status')||'');if(!id||!['draft','published','hidden'].includes(status))return{ok:false,message:'وضعیت معتبر نیست.',nonce:Date.now()};const{error}=await a.s.from('pages').update({status,published_at:status==='published'?new Date().toISOString():null,updated_by:a.userId,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:err(error,'تغییر وضعیت انجام نشد.'),nonce:Date.now()};revalidatePath('/admin/pages');return{ok:true,message:status==='published'?'صفحه منتشر شد.':status==='hidden'?'صفحه مخفی شد.':'صفحه به پیش‌نویس رفت.',nonce:Date.now()}}
export async function createBlock(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),pageId=String(f.get('page_id')||''),type=String(f.get('block_type')||'text');const{data:page}=await a.s.from('pages').select('id').eq('id',pageId).eq('tenant_id',a.tenantId).maybeSingle();if(!page)return{ok:false,message:'صفحه در سایت فعال پیدا نشد.',nonce:Date.now()};const{data:last}=await a.s.from('page_blocks').select('position').eq('tenant_id',a.tenantId).eq('page_id',pageId).order('position',{ascending:false}).limit(1).maybeSingle();const defaults:Record<string,object>={hero:{title:'عنوان اصلی',text:'توضیح کوتاه این بخش',button_label:'بیشتر بدانید',button_url:'#'},text:{title:'عنوان بخش',text:'متن این بخش را وارد کنید.'},image:{url:'',alt:'',caption:''},cta:{title:'آماده شروع هستید؟',text:'برای شروع همکاری با ما در تماس باشید.',button_label:'تماس با ما',button_url:'/contact'},gallery:{title:'گالری',images:[]}};const{error}=await a.s.from('page_blocks').insert({tenant_id:a.tenantId,page_id:pageId,block_type:type,position:(last?.position??-1)+1,visible:true,data:defaults[type]??{}});if(error)return{ok:false,message:err(error,'افزودن بلاک انجام نشد.'),nonce:Date.now()};revalidatePath(`/admin/pages/${pageId}`);return{ok:true,message:'بلاک اضافه شد.',nonce:Date.now()}}
function blockData(f:FormData,type:string){let d:Record<string,unknown>={};if(['hero','text','cta'].includes(type))d={title:String(f.get('title')||''),text:String(f.get('text')||'')};if(['hero','cta'].includes(type))d={...d,button_label:String(f.get('button_label')||''),button_url:String(f.get('button_url')||'')};if(type==='image')d={url:String(f.get('url')||''),alt:String(f.get('alt')||''),caption:String(f.get('caption')||'')};if(type==='gallery')d={title:String(f.get('title')||''),images:String(f.get('images')||'').split('\n').map(x=>x.trim()).filter(Boolean)};return d}
export async function updateBlock(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||''),pageId=String(f.get('page_id')||''),type=String(f.get('block_type')||'text');const{error}=await a.s.from('page_blocks').update({data:blockData(f,type),updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:err(error,'ویرایش بلاک انجام نشد.'),nonce:Date.now()};revalidatePath(`/admin/pages/${pageId}`);return{ok:true,message:'تغییرات بلاک ذخیره شد.',nonce:Date.now()}}
export async function toggleBlock(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||''),pageId=String(f.get('page_id')||''),visible=String(f.get('visible'))==='true';const{error}=await a.s.from('page_blocks').update({visible:!visible,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:err(error,'تغییر نمایش انجام نشد.'),nonce:Date.now()};revalidatePath(`/admin/pages/${pageId}`);return{ok:true,message:visible?'بلاک مخفی شد.':'بلاک نمایش داده شد.',nonce:Date.now()}}
export async function moveBlock(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||''),pageId=String(f.get('page_id')||''),dir=String(f.get('direction')||'up');const{data:bs,error}=await a.s.from('page_blocks').select('id,position').eq('tenant_id',a.tenantId).eq('page_id',pageId).order('position');if(error||!bs)return{ok:false,message:err(error,'جابه‌جایی انجام نشد.'),nonce:Date.now()};const i=bs.findIndex(b=>b.id===id),t=dir==='up'?i-1:i+1;if(i<0||t<0||t>=bs.length)return{ok:false,message:'بیشتر قابل جابه‌جایی نیست.',nonce:Date.now()};await a.s.from('page_blocks').update({position:bs[t].position}).eq('id',bs[i].id).eq('tenant_id',a.tenantId);await a.s.from('page_blocks').update({position:bs[i].position}).eq('id',bs[t].id).eq('tenant_id',a.tenantId);revalidatePath(`/admin/pages/${pageId}`);return{ok:true,message:'ترتیب بلاک تغییر کرد.',nonce:Date.now()}}
export async function deleteBlock(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||''),pageId=String(f.get('page_id')||'');const{error}=await a.s.from('page_blocks').delete().eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:err(error,'حذف بلاک انجام نشد.'),nonce:Date.now()};revalidatePath(`/admin/pages/${pageId}`);return{ok:true,message:'بلاک حذف شد.',nonce:Date.now()}}
export async function deletePage(_:AdminActionState,f:FormData):Promise<AdminActionState>{const a=await editor(),id=String(f.get('id')||'');if(!id)return{ok:false,message:'شناسه معتبر نیست.',nonce:Date.now()};const{data:p}=await a.s.from('pages').select('title').eq('id',id).eq('tenant_id',a.tenantId).maybeSingle();if(!p)return{ok:false,message:'صفحه در سایت فعال پیدا نشد.',nonce:Date.now()};const{error}=await a.s.from('pages').delete().eq('id',id).eq('tenant_id',a.tenantId);if(error)return{ok:false,message:err(error,'حذف صفحه انجام نشد.'),nonce:Date.now()};revalidatePath('/admin/pages');return{ok:true,message:`صفحه «${p.title}» حذف شد.`,redirectTo:'/admin/pages',nonce:Date.now()}}
