'use server'

import { createClient as createAdminClient } from '@supabase/supabase-js'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { logEvent } from '@/lib/observability/logger'
import type { AdminActionState } from '@/app/admin/components/ActionForm'

const ROLES=['admin','content_manager','crm','viewer'] as const
async function requireSuperAdmin(){const supabase=await createClient();const{data:claims}=await supabase.auth.getClaims();const userId=claims?.claims?.sub;if(!userId)redirect('/login');const{data:p}=await supabase.from('profiles').select('role,active').eq('id',userId).single();if(!p?.active||p.role!=='super_admin')redirect('/admin');return{supabase,userId}}
export async function createAdminUser(_state:AdminActionState,formData:FormData):Promise<AdminActionState>{const{userId}=await requireSuperAdmin();const email=String(formData.get('email')||'').trim().toLowerCase(),displayName=String(formData.get('display_name')||'').trim(),role=String(formData.get('role')||'viewer');if(!email||email.length>254||!displayName||displayName.length>120||!ROLES.includes(role as any))return{ok:false,message:'اطلاعات کاربر معتبر نیست.',nonce:Date.now()};const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return{ok:false,message:'تنظیمات ایجاد کاربر روی سرور کامل نیست.',nonce:Date.now()};const admin=createAdminClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const{data,error}=await admin.auth.admin.inviteUserByEmail(email,{data:{display_name:displayName}});if(error||!data.user){const errorId=await logEvent({category:'error',eventName:'users.invite.failed',message:'Admin invitation failed',actorUserId:userId,error,metadata:{emailDomain:email.split('@')[1]||''}});return{ok:false,message:`ارسال دعوت انجام نشد. کد پیگیری: ${errorId}`,nonce:Date.now()}}await admin.from('profiles').update({display_name:displayName,role,active:true}).eq('id',data.user.id);await logEvent({category:'audit',eventName:'users.invited',message:'Administrative user invited',actorUserId:userId,summaryFa:'یک کاربر مدیریتی جدید دعوت شد.',causeFa:'این دعوت توسط سوپر ادمین از بخش مدیریت کاربران انجام شده است.',metadata:{target_user_id:data.user.id,role}});revalidatePath('/admin/users');return{ok:true,message:'دعوت کاربر مدیریتی با موفقیت ارسال شد.',nonce:Date.now()}}
export async function updateAdminUser(_state:AdminActionState,formData:FormData):Promise<AdminActionState>{const{supabase}=await requireSuperAdmin();const id=String(formData.get('user_id')||''),name=String(formData.get('display_name')||'').trim(),role=String(formData.get('role')||''),active=String(formData.get('active'))==='true';if(!id||!name||!ROLES.includes(role as any))return{ok:false,message:'اطلاعات کاربر معتبر نیست.',nonce:Date.now()};const{error}=await supabase.rpc('super_admin_update_user',{p_user_id:id,p_display_name:name,p_role:role,p_active:active});if(error)return{ok:false,message:'ویرایش کاربر انجام نشد.',nonce:Date.now()};revalidatePath('/admin/users');revalidatePath('/admin/access');return{ok:true,message:'تغییرات کاربر با موفقیت ذخیره شد.',nonce:Date.now()}}
export async function revokeUserSessions(_state:AdminActionState,formData:FormData):Promise<AdminActionState>{const{supabase}=await requireSuperAdmin();const id=String(formData.get('user_id')||'');if(!id)return{ok:false,message:'شناسه کاربر معتبر نیست.',nonce:Date.now()};const{data,error}=await supabase.rpc('super_admin_revoke_user_sessions',{p_user_id:id});if(error)return{ok:false,message:'بستن نشست‌ها انجام نشد.',nonce:Date.now()};revalidatePath('/admin/users');return{ok:true,message:`${Number(data||0).toLocaleString('fa-IR')} نشست فعال بسته شد.`,nonce:Date.now()}}
