'use client'

import Link from 'next/link'
import AdminIcon from './AdminIcon'
import {useAdminLocale} from './AdminLocale'

type Props={siteCount:number;siteId:string|null;siteName:string|null;pageCount:number;mediaCount:number;starterInstalled:boolean;designReady:boolean;releasePublished:boolean;displayName:string}
const text={
  fa:{eyebrow:'راه‌اندازی ساده راوا',title:(name:string)=>`${name}، فقط قدم بعدی را انجام دهید`,summary:'راوا کارهای فنی را پشت صحنه انجام می‌دهد. شما فقط اطلاعات واقعی را بررسی می‌کنید و هیچ چیزی بدون پیش‌نمایش و تأیید منتشر نمی‌شود.',progress:'پیشرفت راه‌اندازی',next:'قدم بعدی',done:'انجام‌شده',current:'الان انجام دهید',pending:'بعداً',open:'رفتن به این مرحله',activeSite:'سایت در حال راه‌اندازی',steps:['ساخت سایت','انتخاب محتوای آماده','تکمیل محتوا و رسانه‌ها','انتخاب ظاهر سایت','پیش‌نمایش و تأیید انتشار'],descriptions:['نام مشتری و سایت را وارد کنید؛ ساختار فنی خودکار آماده می‌شود.','حوزه کسب‌وکار و بسته محتوای مناسب را انتخاب کنید.','اطلاعات برند، خدمات، صفحه‌ها، تصاویر و ویدیوها را بررسی کنید.','قالب، رنگ و قلم را در پیش‌نمایش انتخاب کنید.','نسخه نهایی را ببینید و فقط پس از تأیید منتشر کنید.']},
  en:{eyebrow:'Simple RAVA setup',title:(name:string)=>`${name}, only focus on the next step`,summary:'RAVA handles technical work behind the scenes. You review real business information, and nothing is published without preview and approval.',progress:'Setup progress',next:'Next step',done:'Completed',current:'Do this now',pending:'Later',open:'Open this step',activeSite:'Site being set up',steps:['Create the site','Choose ready-made content','Complete content and media','Choose the site appearance','Preview and approve release'],descriptions:['Enter the customer and site names; the technical structure is created automatically.','Choose the business field and suitable content pack.','Review brand facts, services, pages, images, and videos.','Choose a template, colors, and typeface in preview.','Review the final version and publish only after approval.']},
}
export default function GettingStarted({siteCount,siteId,siteName,pageCount,mediaCount,starterInstalled,designReady,releasePublished,displayName}:Props){
  const{language}=useAdminLocale(),t=text[language],stepDone=[siteCount>0,starterInstalled,pageCount>0&&mediaCount>0,designReady,releasePublished],firstIncomplete=stepDone.findIndex(done=>!done),completed=stepDone.filter(Boolean).length,setupComplete=completed===5,current=firstIncomplete===-1?5:firstIncomplete+1,siteHome=siteId?`/admin/platform/sites/${siteId}`:'/admin/platform/sites/new'
  const hrefs=['/admin/platform/sites/new',siteId?`${siteHome}/starter`:siteHome,siteId?`/admin/pages?site=${siteId}`:'/admin/pages',siteId?`${siteHome}/design#appearance`:siteHome,siteId?`${siteHome}/design#release`:siteHome]
  return <section className="rava-getting-started" aria-labelledby="getting-started-title"><header><div><span className="eyebrow">{t.eyebrow}</span><h1 id="getting-started-title">{t.title(displayName)}</h1><p>{t.summary}</p>{siteName?<small className="rava-active-setup-site">{t.activeSite}: <b>{siteName}</b></small>:null}</div><div className="rava-progress-card"><span>{t.progress}</span><b>{completed} / 5</b><div><i style={{width:`${completed/5*100}%`}}/></div></div></header><div className="rava-journey">{t.steps.map((label,index)=>{const number=index+1,status=stepDone[index]?'done':number===current?'current':'pending';return <Link href={hrefs[index]} className={`rava-journey-step is-${status}`} key={label} aria-label={`${number}. ${label}`}><div className="rava-step-marker"><b>{number}</b>{index<t.steps.length-1&&<span><AdminIcon name="arrow" size={17}/></span>}</div><div className="rava-step-copy"><div><h2>{label}</h2><span className="rava-status-pill">{status==='done'?t.done:status==='current'?t.current:t.pending}</span></div><p>{t.descriptions[index]}</p><span className="rava-step-link">{t.open}<AdminIcon name="arrow" size={16}/></span></div></Link>})}</div><footer><span>{setupComplete?t.done:t.next}</span><strong>{setupComplete?t.steps[4]:`${current}. ${t.steps[current-1]}`}</strong>{siteCount>0?<small>{pageCount} {language==='fa'?'صفحه':'pages'} · {mediaCount} {language==='fa'?'رسانه':'media items'}</small>:null}</footer></section>
}
