'use client'

import Link from 'next/link'
import AdminIcon from './AdminIcon'
import {useAdminLocale} from './AdminLocale'

type Props={siteCount:number;pageCount:number;mediaCount:number;displayName:string}
const text={
  fa:{eyebrow:'شروع کار با راوا',title:(name:string)=>`${name}، قدم بعدی کاملاً مشخص است`,summary:'برای راه‌اندازی درست، این مسیر را به‌ترتیب جلو بروید. اطلاعات شما میان مراحل حفظ می‌شود و هیچ چیزی بدون پیش‌نمایش و تأیید منتشر نخواهد شد.',progress:'پیشرفت راه‌اندازی',next:'قدم بعدی پیشنهادی',done:'انجام شده',current:'در حال انجام',pending:'در انتظار',locked:'پس از تکمیل مراحل قبل',open:'ادامه این مرحله',steps:['حساب مالک و امنیت','ساخت سایت و محیط‌ها','نصب محتوای مناسب کسب‌وکار','تکمیل اطلاعات واقعی برند','چیدن منو و صفحه‌ها','انتخاب ظاهر و قالب','بازبینی کامل در پیش‌نمایش','تأیید و انتشار کنترل‌شده'],descriptions:['مالک پلتفرم با ورود امن فعال شده است.','سایت، محیط آزمایشی و ساختار پایه آماده است.','صفحه‌های فارسی و انگلیسی به‌صورت پیش‌نویس ساخته شده‌اند.','خدمات، راه‌های تماس و واقعیت‌های قابل تأیید را کامل کنید.','صفحه‌ها را مرتب کنید و مسیر دسترسی بازدیدکننده را بسازید.','رنگ، فونت و قالب نسخه‌دار را انتخاب و مقایسه کنید.','نسخه نهایی را بدون نمایش عمومی بررسی کنید.','فقط پس از عبور کنترل‌ها، انتشار را تأیید کنید.']},
  en:{eyebrow:'Getting started with RAVA',title:(name:string)=>`${name}, your next step is clear`,summary:'Follow this guided path in order. Your progress is preserved, and nothing is published without a preview and explicit approval.',progress:'Setup progress',next:'Recommended next step',done:'Completed',current:'In progress',pending:'Waiting',locked:'Complete earlier steps first',open:'Continue this step',steps:['Owner account & security','Create the site and environments','Install business-ready starter content','Complete verified brand details','Arrange navigation and pages','Choose the visual system and template','Review the complete preview','Approve a controlled release'],descriptions:['The platform owner is active with secure access.','The site, staging environment and core structure are ready.','English and Persian pages were created as drafts.','Add approved services, contact channels and verifiable facts.','Organize pages and create a clear visitor journey.','Compare and select versioned colors, type and templates.','Review the final experience without making it public.','Publish only after every release gate passes.']},
}
export default function GettingStarted({siteCount,pageCount,mediaCount,displayName}:Props){
  const{language}=useAdminLocale(),t=text[language]
  const completed=pageCount>0?3:siteCount>0?2:1,current=Math.min(completed+1,8)
  const hrefs=['/admin/system/access','/admin/platform/sites','/admin/pages','/admin/pages','/admin/pages','/admin/platform/sites','/admin/pages','#']
  return <section className="rava-getting-started" aria-labelledby="getting-started-title"><header><div><span className="eyebrow">{t.eyebrow}</span><h1 id="getting-started-title">{t.title(displayName)}</h1><p>{t.summary}</p></div><div className="rava-progress-card"><span>{t.progress}</span><b>{completed} / 8</b><div><i style={{width:`${completed/8*100}%`}}/></div></div></header><div className="rava-journey">{t.steps.map((label,index)=>{
    const number=index+1,status=number<=completed?'done':number===current?'current':number>current+1?'locked':'pending'
    return <article className={`rava-journey-step is-${status}`} key={label}><div className="rava-step-marker"><b>{number}</b>{index<t.steps.length-1&&<span><AdminIcon name="arrow" size={17}/></span>}</div><div className="rava-step-copy"><div><h2>{label}</h2><span className="rava-status-pill">{status==='done'?t.done:status==='current'?t.current:status==='locked'?t.locked:t.pending}</span></div><p>{t.descriptions[index]}</p>{status==='current'&&<Link href={hrefs[index]}>{t.open}<AdminIcon name="arrow" size={16}/></Link>}</div></article>})}</div><footer><span>{t.next}</span><strong>{current}. {t.steps[current-1]}</strong><small>{pageCount} {language==='fa'?'صفحه پیش‌نویس':'draft pages'} · {mediaCount} {language==='fa'?'فایل رسانه‌ای':'media files'}</small></footer></section>
}
