insert into public.admin_help_items(help_key,title_fa,body_fa,title_en,body_en,warning_fa,warning_en) values
('tenant.active_context','سایت فعال در پنل','تمام عملیات، آمار، رسانه، پروژه‌ها و کاربران پنل بر اساس Tenant فعال فیلتر می‌شوند. نام سایت فعال همیشه در منوی مدیریت نمایش داده می‌شود.','Active site context','All admin operations, analytics, media, projects and users are scoped to the active tenant. The active site name is always shown in admin navigation.',null,null),
('tenant.switch','تغییر سایت فعال','این گزینه فقط محیط مدیریتی فعال را به مشتری دیگری تغییر می‌دهد و داده‌ای را جابه‌جا یا کپی نمی‌کند.','Switch active tenant','This only changes the active management context to another tenant. It does not move or copy any tenant data.',null,null),
('tenant.status','وضعیت سایت مشتری','Active سایت را عادی نگه می‌دارد؛ Maintenance صفحه تعمیرات نشان می‌دهد؛ Read-only و Suspended نوشتن مشتری را در سطح دیتابیس متوقف می‌کنند.','Tenant status','Active serves normally; Maintenance shows a maintenance page; Read-only and Suspended block customer writes at the database layer.','تعلیق یا Read-only روی دسترسی مشتری اثر مستقیم دارد. قبل از تأیید، Tenant و علت عملیات را دوباره بررسی کنید.','Suspension or Read-only directly affects customer access. Verify the tenant and reason before confirming.'),
('tenant.isolation','ایزوله‌سازی مشتری‌ها','هر داده با tenant_id مشخص می‌شود و RLS دسترسی بین مشتری‌ها را مسدود می‌کند. Platform Staff نیز فقط در محدوده Tenant Scope خود دسترسی دارد.','Tenant isolation','Every tenant-owned record is scoped by tenant_id and RLS blocks cross-tenant access. Platform staff are also limited by their tenant scope.','تغییر Policy یا Tenant Scope می‌تواند روی جداسازی اطلاعات مشتری‌ها اثر بگذارد و باید با Audit کامل انجام شود.','Changing policies or tenant scope can affect customer data isolation and must be performed with full auditability.'),
('platform.staff.role','نقش نیروی RAVA','Platform Admin دسترسی مدیریتی سراسری دارد؛ SEO Manager فقط عملیات SEO و آمار مجاز را انجام می‌دهد؛ Content Ops محتوا را مدیریت می‌کند و Support برای پشتیبانی استفاده می‌شود.','RAVA staff role','Platform Admin has platform-wide administration; SEO Manager is limited to SEO and permitted analytics; Content Ops manages content and Support is for support operations.','نقش بیشتر از نیاز واقعی به نیرو ندهید. اصل حداقل دسترسی الزامی است.','Do not grant a role broader than necessary. Least privilege is required.'),
('platform.staff.scope','محدوده مشتری‌های نیروی RAVA','برای نقش‌های غیرسراسری مشخص می‌کند نیرو دقیقاً به کدام مشتری‌ها دسترسی دارد. این محدودیت در دیتابیس نیز enforce می‌شود.','RAVA staff tenant scope','Defines exactly which tenants a non-global RAVA staff member may access. The restriction is also enforced at the database layer.','اشتباه در Tenant Scope ممکن است اطلاعات مشتری نامرتبط را در دسترس نیرو قرار دهد. انتخاب‌ها را قبل از ذخیره بررسی کنید.','An incorrect tenant scope may expose an unrelated client to a staff member. Review selections before saving.'),
('seo.managed_service','سرویس Managed SEO','مشتری همیشه می‌تواند SEO پایه را دستی مدیریت کند. ابزارهای اتوماتیک فقط زمانی فعال‌اند که سرویس Managed SEO خریداری شده باشد و فقط نیروی مجاز RAVA آن‌ها را اجرا می‌کند.','Managed SEO service','Customers can always manage basic SEO manually. Automation is enabled only when Managed SEO is purchased and is executed only by authorized RAVA staff.',null,null)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_fa=excluded.warning_fa,warning_en=excluded.warning_en,updated_at=now();
