-- Bilingual contextual guidance for Order Lifecycle / Return / Refund / Reconciliation.
insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('orders.lifecycle','چرخه سفارش','وضعیت سفارش و اجرای آن را از ثبت تا تأیید، آماده‌سازی، ارسال، تحویل، تکمیل یا لغو مدیریت می‌کند. مسیرهای عادی می‌توانند خودکار جلو بروند و مدیر برای شرایط استثنایی امکان Override دستی دارد.','تغییر دستی وضعیت، واقعیت قبلی را پاک نمی‌کند و باید در تاریخچه و Audit ثبت شود.','Order lifecycle','Manage an order from creation through confirmation, preparation, shipment, delivery, completion or cancellation. Normal flows may advance automatically, while managers retain manual override for exceptional cases.','Manual state changes must not erase prior history and must remain auditable.',true),
('orders.shipment','مرسوله و رهگیری','برای هر سفارش می‌توان شرکت حمل، کد رهگیری، لینک رهگیری و وضعیت مرسوله را ثبت و ویرایش کرد. وضعیت مرسوله می‌تواند Fulfillment سفارش را در مسیر عادی به‌روزرسانی کند.','ارسال یا تحویل سفارش پرداخت‌نشده فقط باید با قواعد مجاز سیستم یا Override مدیریتی ثبت‌شده انجام شود.','Shipment and tracking','Record and edit the carrier, tracking code, tracking link and shipment status. Shipment progress can automatically advance order fulfillment in the normal flow.','Shipping or delivering an unpaid order must only occur through allowed rules or an audited manager override.',true),
('orders.return','مرجوعی کالا','مرجوعی به همان سفارش و آیتم‌های خرید متصل می‌ماند. مدیر مشخص می‌کند چه تعداد سالم برگشته، چه تعداد آسیب‌دیده است و چه مبلغی برای بازپرداخت در نظر گرفته شود.','تعداد مرجوعی نباید از تعداد خرید بیشتر شود و کالای آسیب‌دیده نباید خودکار به موجودی قابل فروش برگردد.','Returns','A return remains linked to its original order and purchased items. Managers record sellable returned quantities, damaged quantities and the amount considered for refund.','Returned quantity cannot exceed purchased quantity, and damaged goods must not automatically return to sellable stock.',true),
('orders.restock','بازگشت کالا به انبار','فقط تعداد سالم و تأییدشده می‌تواند به انبار انتخاب‌شده Restock شود. ورود مجدد موجودی در Ledger ثبت می‌شود تا منشأ افزایش موجودی مشخص بماند.','Restock را فقط بعد از دریافت و بررسی فیزیکی کالا تأیید کن.','Return restocking','Only confirmed sellable quantities should be restocked into the selected inventory location. Restocking is written to the inventory ledger so the source of stock changes remains traceable.','Confirm restocking only after the returned goods have been physically received and inspected.',true),
('orders.refund','بازپرداخت وجه','Refund می‌تواند کامل یا جزئی باشد و وضعیت‌هایی مثل برنامه‌ریزی‌شده، در انتظار، در حال پردازش، موفق یا ناموفق داشته باشد. ثبت Refund مدیریتی با اجرای واقعی بازپرداخت از درگاه یکسان نیست.','برچسب موفقیت درگاه فقط باید از Payment Engine معتبر ثبت شود؛ مدیر نباید Refund دستی را به‌عنوان Gateway Success جا بزند.','Refunds','Refunds may be full or partial and can move through planned, requested, processing, succeeded or failed states. A manager-recorded refund is not the same as a refund executed and verified by a payment provider.','Gateway success must only be recorded by the trusted Payment Engine; a manual refund must never be presented as provider-confirmed.',true),
('orders.reconciliation','هماهنگ‌سازی خودکار سفارش','Auto Reconciliation اتفاقات مرتبط را هماهنگ می‌کند؛ برای نمونه لغو سفارش می‌تواند رزرو موجودی را آزاد کند، مرسوله ارسال‌نشده را لغو کند و در سفارش پرداخت‌شده نیاز به Refund را برنامه‌ریزی کند.','اتوماسیون مالی نباید بدون تأیید Payment Provider پول جابه‌جا کند. Override دستی همچنان باید دلیل و Audit داشته باشد.','Automatic order reconciliation','Auto Reconciliation coordinates related operations. For example, cancellation can release inventory reservations, cancel unshipped parcels and plan the remaining refund amount for a paid order.','Financial automation must not move money without trusted payment-provider confirmation. Manual overrides must remain reasoned and auditable.',true),
('orders.manual_override','تغییر دستی مدیریتی','برای شرایط استثنایی مدیر می‌تواند جریان خودکار را Override کند. مقدار قبل و بعد، دلیل، زمان و مدیر انجام‌دهنده باید در تاریخچه باقی بماند.','Override ابزار اصلاح استثناست، نه راه حذف سابقه یا جعل پرداخت و ارسال.','Manager manual override','Managers can override the automatic flow for exceptional cases. Previous and new values, reason, timestamp and acting manager must remain in history.','Override is for resolving exceptions, not erasing history or fabricating payment or shipment evidence.',true),
('inventory.manual_adjustment','اصلاح دستی موجودی','مدیر می‌تواند موجودی یک Variant را برای شمارش فیزیکی، خرابی، کسری، هدیه، برگشت کالا یا اصلاح مدیریتی افزایش یا کاهش دهد. دلیل تغییر اجباری است و حرکت در Ledger ثبت می‌شود.','موجودی واقعی نباید با اصلاح دستی منفی شود و تاریخچه Ledger نباید پاک یا بازنویسی شود.','Manual inventory adjustment','Managers can increase or decrease a variant stock level for physical counts, damage, shortages, giveaways, returns or other administrative corrections. A reason is required and the movement is recorded in the ledger.','Manual adjustment must not create negative on-hand stock, and ledger history must not be erased or rewritten.',true),
('inventory.reservation','رزرو موجودی','رزرو باعث می‌شود کالایی که در Checkout یا سفارش درگیر است هم‌زمان دوباره فروخته نشود. در لغو یا خطای پرداخت، رزرو می‌تواند خودکار یا با دلیل به‌صورت دستی آزاد شود.','آزادسازی دستی رزرو را فقط وقتی انجام بده که مطمئنی سفارش دیگر به آن موجودی نیاز ندارد.','Inventory reservation','Reservations prevent stock already involved in checkout or an order from being sold again. On cancellation or payment failure, reservations may be released automatically or manually with a recorded reason.','Manually release a reservation only when the order no longer requires that stock.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;
