insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('commerce.reviews','نظرات و امتیازها','اینجا Reviewها، امتیازها و پرسش‌های محصول را مدیریت می‌کنی. برچسب خریدار تأییدشده فقط باید از سفارش واقعی و معتبر ساخته شود.',null,'Reviews & ratings','Manage product reviews, ratings and questions here. Verified-purchase status must only come from a real valid order.',null,true),
('commerce.reviews.moderation','مدیریت نظرها','مدیر می‌تواند نظر را منتشر، مخفی، رد، Spam یا Deleted کند. حتی نظر منفی هم قابل حذف است. هر تغییر مدیریتی Audit Log دارد.','حذف یا مخفی‌کردن نظر روی امتیاز و اعتماد مشتری اثر می‌گذارد؛ قبل از اعمال، Review صحیح را بررسی کن.','Review moderation','Admins may publish, hide, reject, mark spam or delete any review, including negative reviews. Every moderation action is audited.','Moderation changes product trust and rating. Verify the correct review before applying.',true),
('commerce.reviews.settings','تنظیمات Review','می‌توانی تأیید قبل از انتشار، عکس/ویدیو، Q&A، پاسخ مشتری، فقط خریدار تأییدشده و درخواست Review بعد از خرید را کنترل کنی.',null,'Review settings','Control moderation, media, Q&A, customer answers, verified-purchase-only mode and post-purchase review requests.',null,true),
('commerce.reviews.dimensions','معیارهای امتیازدهی','برای هر دسته می‌توان معیارهایی مثل کیفیت، تطابق سایز، جنس و ارزش خرید تعریف کرد. امتیاز هر معیار بین ۱ تا ۵ است.',null,'Rating dimensions','Define category-specific dimensions such as quality, fit, material and value. Each score is 1 to 5.',null,true),
('commerce.reviews.insights','تحلیل رضایت','این بخش روند امتیازها و موضوعات پرتکرار مثبت و منفی را نگه می‌دارد. AI Insights فقط خلاصه مدیریتی تولید می‌کند و جای داده واقعی Reviewها را نمی‌گیرد.',null,'Review insights','Tracks rating trends and recurring positive/negative themes. AI Insights summarizes real review data and does not replace it.',null,true),
('commerce.qna','پرسش‌وپاسخ محصول','پرسش‌های قبل از خرید از Review جدا هستند. مدیر می‌تواند آن‌ها را تأیید، مخفی یا حذف کند و پاسخ رسمی فروشگاه هم قابل ثبت است.',null,'Product Q&A','Pre-purchase questions are separate from reviews. Admins can moderate them and provide official merchant answers.',null,true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;
insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('commerce.reviews.workflow','commerce','/admin/commerce/reviews','مدیریت اعتماد، Review و Q&A','راهنمای Review، خریدار تأییدشده، رسانه، Moderation و تحلیل رضایت','Reviewها می‌توانند ۱ تا ۵ ستاره، متن، معیارهای جزئی و عکس/ویدیو داشته باشند. خریدار تأییدشده فقط از سفارش معتبر مشخص می‌شود. مدیر کنترل کامل انتشار، مخفی‌کردن، رد و حذف را دارد و تمام اقدامات مدیریتی لاگ می‌شوند. Helpful و Report برای مرتب‌سازی و تشخیص محتوای مشکل‌دار استفاده می‌شوند. Q&A از Review جداست. درخواست Review می‌تواند چند روز بعد از خرید زمان‌بندی شود. AI Insights در صورت فعال‌بودن، موضوعات پرتکرار مثبت و منفی را به‌صورت خلاصه مدیریتی نمایش می‌دهد.','Trust, reviews & Q&A','Guide to verified purchases, media, moderation and satisfaction insights','Reviews support 1–5 stars, text, dimension scores and media. Verified purchase is derived only from a valid order. Admins have full moderation control and all actions are audited. Helpful and Report signals support ranking and abuse detection. Q&A is separate from reviews. Review requests can be scheduled after purchase. Optional AI Insights summarize recurring positive and negative themes.',array['review','rating','نظر','امتیاز','خریدار تاییدشده','q&a','helpful','moderation','رضایت'],'important',array['commerce.reviews','commerce.reviews.moderation','commerce.reviews.settings','commerce.reviews.insights','commerce.qna'],true,21)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;