-- RAVA Inventory Pro. Requires entitlement inventory.pro in application/server actions.
create table if not exists public.inventory_locations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,name text not null,code text not null,address jsonb not null default '{}'::jsonb,active boolean not null default true,is_default boolean not null default false,created_at timestamptz not null default now(),unique(tenant_id,code));
create table if not exists public.inventory_balances(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,location_id uuid not null references public.inventory_locations(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,on_hand int not null default 0,reserved int not null default 0 check(reserved>=0),reorder_point int not null default 0 check(reorder_point>=0),updated_at timestamptz not null default now(),unique(location_id,product_id),check(on_hand>=0),check(reserved<=on_hand));
create table if not exists public.inventory_ledger(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,location_id uuid not null references public.inventory_locations(id) on delete restrict,product_id uuid not null references public.products(id) on delete restrict,movement_type text not null check(movement_type in('receipt','sale','reservation','reservation_release','return','damage','adjustment','transfer_in','transfer_out')),quantity_delta int not null,reference_type text,reference_id uuid,reason text not null default '',actor_user_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.inventory_reservations(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,location_id uuid not null references public.inventory_locations(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,cart_id uuid references public.carts(id) on delete cascade,order_id uuid references public.orders(id) on delete cascade,quantity int not null check(quantity>0),status text not null default 'active' check(status in('active','committed','released','expired')),expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.inventory_transfers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,from_location_id uuid not null references public.inventory_locations(id) on delete restrict,to_location_id uuid not null references public.inventory_locations(id) on delete restrict,status text not null default 'draft' check(status in('draft','in_transit','received','cancelled')),notes text not null default '',created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),received_at timestamptz,check(from_location_id<>to_location_id));
create table if not exists public.inventory_transfer_items(id uuid primary key default gen_random_uuid(),transfer_id uuid not null references public.inventory_transfers(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,quantity int not null check(quantity>0),unique(transfer_id,product_id));
create index if not exists inventory_balances_tenant_product_idx on public.inventory_balances(tenant_id,product_id);create index if not exists inventory_ledger_lookup_idx on public.inventory_ledger(tenant_id,product_id,created_at desc);create index if not exists inventory_reservations_expiry_idx on public.inventory_reservations(tenant_id,status,expires_at);
alter table public.inventory_locations enable row level security;alter table public.inventory_balances enable row level security;alter table public.inventory_ledger enable row level security;alter table public.inventory_reservations enable row level security;alter table public.inventory_transfers enable row level security;alter table public.inventory_transfer_items enable row level security;
create policy inventory_locations_admin on public.inventory_locations for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));create policy inventory_balances_admin on public.inventory_balances for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy inventory_ledger_admin on public.inventory_ledger for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy inventory_reservations_admin on public.inventory_reservations for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy inventory_transfers_admin on public.inventory_transfers for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy inventory_transfer_items_admin on public.inventory_transfer_items for select to authenticated using(exists(select 1 from public.inventory_transfers t where t.id=transfer_id and public.can_access_tenant(t.tenant_id,null)));
-- Balance/ledger/reservation mutations intentionally have no direct client write policies. Trusted server functions must check inventory.pro, lock rows and write ledger + balance atomically.
