-- RAVA Persistent Cart Engine
alter table public.carts add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.carts add column if not exists last_activity_at timestamptz not null default now();
alter table public.carts add column if not exists abandoned_at timestamptz;
alter table public.cart_items add column if not exists state text not null default 'cart' check(state in('cart','saved'));
create unique index if not exists carts_one_open_user_tenant_uq on public.carts(tenant_id,user_id) where user_id is not null and status='open';
create index if not exists carts_abandoned_scan_idx on public.carts(status,last_activity_at) where status='open';
create index if not exists cart_items_cart_state_idx on public.cart_items(cart_id,state);

create or replace function public.customer_cart_snapshot(p_tenant uuid) returns jsonb language plpgsql security definer set search_path=public as $$
declare c uuid;begin
 if auth.uid() is null then raise exception 'authentication_required';end if;
 select id into c from public.carts where tenant_id=p_tenant and user_id=auth.uid() and status='open' order by updated_at desc limit 1;
 if c is null then return jsonb_build_object('cart_id',null,'items','[]'::jsonb);end if;
 return jsonb_build_object('cart_id',c,'items',coalesce((select jsonb_agg(jsonb_build_object('variantId',ci.variant_id,'quantity',ci.quantity,'state',ci.state,'name',p.name,'variantTitle',v.title,'price',v.price,'currency',v.currency,'stock',case when v.track_inventory then v.inventory_quantity else null end) order by ci.id) from public.cart_items ci join public.product_variants v on v.id=ci.variant_id and v.tenant_id=p_tenant join public.products p on p.id=v.product_id and p.tenant_id=p_tenant where ci.cart_id=c and ci.tenant_id=p_tenant),'[]'::jsonb));
end$$;
revoke all on function public.customer_cart_snapshot(uuid) from public,anon;grant execute on function public.customer_cart_snapshot(uuid) to authenticated;

create or replace function public.merge_customer_cart(p_tenant uuid,p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare c uuid;x jsonb;v uuid;q int;existing int;begin
 if auth.uid() is null then raise exception 'authentication_required';end if;if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)>50 then raise exception 'invalid_items';end if;
 insert into public.carts(tenant_id,user_id,status,currency,last_activity_at,updated_at) values(p_tenant,auth.uid(),'open','IRR',now(),now()) on conflict(tenant_id,user_id) where user_id is not null and status='open' do update set last_activity_at=now(),updated_at=now(),abandoned_at=null returning id into c;
 for x in select * from jsonb_array_elements(p_items) loop v:=nullif(x->>'variantId','')::uuid;q:=coalesce((x->>'quantity')::int,0);if q<1 or q>99 then raise exception 'invalid_quantity';end if;if not exists(select 1 from public.product_variants pv join public.products p on p.id=pv.product_id where pv.id=v and pv.tenant_id=p_tenant and p.tenant_id=p_tenant and p.status='active') then continue;end if;select quantity into existing from public.cart_items where cart_id=c and variant_id=v;if existing is null then insert into public.cart_items(tenant_id,cart_id,variant_id,quantity,unit_price,snapshot,state) select p_tenant,c,pv.id,q,pv.price,jsonb_build_object('product_id',pv.product_id,'merged_at',now()),'cart' from public.product_variants pv where pv.id=v and pv.tenant_id=p_tenant;else update public.cart_items set quantity=least(99,greatest(existing,q)),unit_price=(select price from public.product_variants where id=v),state='cart',snapshot=snapshot||jsonb_build_object('merged_at',now()) where cart_id=c and variant_id=v;end if;existing:=null;end loop;
 return public.customer_cart_snapshot(p_tenant);
end$$;
revoke all on function public.merge_customer_cart(uuid,jsonb) from public,anon;grant execute on function public.merge_customer_cart(uuid,jsonb) to authenticated;

create or replace function public.set_customer_cart_item(p_tenant uuid,p_variant uuid,p_quantity int,p_state text default 'cart') returns jsonb language plpgsql security definer set search_path=public as $$declare c uuid;price_now numeric;begin
 if auth.uid() is null then raise exception 'authentication_required';end if;if p_state not in('cart','saved') then raise exception 'invalid_state';end if;if p_quantity<0 or p_quantity>99 then raise exception 'invalid_quantity';end if;select price into price_now from public.product_variants v join public.products p on p.id=v.product_id where v.id=p_variant and v.tenant_id=p_tenant and p.tenant_id=p_tenant and p.status='active';if price_now is null then raise exception 'variant_not_available';end if;
 insert into public.carts(tenant_id,user_id,status,currency,last_activity_at,updated_at) values(p_tenant,auth.uid(),'open','IRR',now(),now()) on conflict(tenant_id,user_id) where user_id is not null and status='open' do update set last_activity_at=now(),updated_at=now(),abandoned_at=null returning id into c;
 if p_quantity=0 then delete from public.cart_items where cart_id=c and variant_id=p_variant;else insert into public.cart_items(tenant_id,cart_id,variant_id,quantity,unit_price,state) values(p_tenant,c,p_variant,p_quantity,price_now,p_state) on conflict(cart_id,variant_id) do update set quantity=excluded.quantity,unit_price=excluded.unit_price,state=excluded.state;end if;update public.carts set last_activity_at=now(),updated_at=now(),abandoned_at=null where id=c;return public.customer_cart_snapshot(p_tenant);end$$;
revoke all on function public.set_customer_cart_item(uuid,uuid,int,text) from public,anon;grant execute on function public.set_customer_cart_item(uuid,uuid,int,text) to authenticated;

create or replace function public.mark_abandoned_carts(p_before interval default interval '24 hours') returns integer language plpgsql security definer set search_path=public as $$declare n int;begin update public.carts set abandoned_at=coalesce(abandoned_at,now()),updated_at=now() where status='open' and user_id is not null and last_activity_at<now()-p_before and abandoned_at is null;get diagnostics n=row_count;return n;end$$;revoke all on function public.mark_abandoned_carts(interval) from public,anon,authenticated;grant execute on function public.mark_abandoned_carts(interval) to service_role;

insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('commerce.cart.persistence','سبد خرید ماندگار','سبد مهمان در مرورگر نگه‌داری می‌شود. پس از ورود مشتری، اقلام با سبد امن سمت سرور ادغام می‌شوند تا روی دستگاه‌های مختلف قابل ادامه باشد.','قیمت و موجودی ذخیره‌شده در سبد مبنای سفارش نیست و Checkout باید همیشه آن‌ها را دوباره از دیتابیس معتبر بخواند.','Persistent cart','Guest carts remain in the browser. After sign-in, items merge into the authenticated server cart so shopping can continue across devices.','Stored cart price and stock are never authoritative; checkout must always revalidate them against trusted server data.',true),
('commerce.cart.saved','ذخیره برای بعد','هر آیتم سبد می‌تواند بدون حذف کامل به حالت «ذخیره برای بعد» منتقل شود و سپس دوباره به سبد خرید برگردد.',null,'Save for later','A cart item can move to a saved state without being deleted and can later be restored to the active cart.',null,true),
('commerce.cart.abandoned','سبد رهاشده','سبدهای مشتری لاگین‌شده بر اساس آخرین فعالیت قابل علامت‌گذاری به‌عنوان رهاشده هستند تا در صورت فعال‌بودن ماژول بازاریابی، بازیابی سبد روی آن‌ها ساخته شود.','علامت رهاشدگی نباید باعث ارسال خودکار پیام شود مگر رضایت بازاریابی و تنظیمات Notification جداگانه بررسی شده باشند.','Abandoned cart','Signed-in carts can be marked abandoned based on last activity so an optional recovery workflow can act on them.','Abandonment alone must never trigger marketing messages unless consent and notification rules are independently satisfied.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;