-- Optional premium renderer: ThreeUI-powered motion with a reduced-motion/WebGL fallback.
insert into public.template_catalog(key,name_fa,name_en,description_fa,description_en,industry_key,status,commercial_tier,is_public,metadata)
values('rava-service-horizon','افق پویا راوا','RAVA Dynamic Horizon','قالب خدماتی حرفه‌ای با عمق بصری پویا، حرکت کنترل‌شده و جایگزین ثابت برای دستگاه‌های کم‌توان یا حالت کاهش حرکت.','A premium service template with controlled visual depth and a static fallback for reduced motion or unavailable WebGL.','services','active','premium',true,'{"family":"services","renderer":"journey","effect":"threeui-emerald-horizon","effect_source":"@designcodeio/threeui@1.1.0","fallback":"static-gradient","starter":false}'::jsonb)
on conflict(key) do update set name_fa=excluded.name_fa,name_en=excluded.name_en,description_fa=excluded.description_fa,description_en=excluded.description_en,industry_key=excluded.industry_key,status=excluded.status,commercial_tier=excluded.commercial_tier,is_public=excluded.is_public,metadata=excluded.metadata,updated_at=now();

insert into public.template_versions(template_id,version,status,theme_defaults,layout_blueprint,seo_defaults,module_defaults,changelog_fa,changelog_en,published_at)
select id,1,'published','{"colors":{"background":"#06133E","surface":"#FFFFFF","text":"#101A38","primary":"#3158BD","accent":"#B8CCFF"},"typography":{"heading":"display-rounded","body":"system"},"radius":28,"spacing":"airy","motion":"ambient"}'::jsonb,'{"renderer":"journey","hero":"dynamic-horizon","effect":{"key":"threeui-emerald-horizon","version":"1.1.0","fallback":"static-gradient","reduced_motion":"static"},"sections":["benefits","story","services-carousel","feature-story","team","mosaic-gallery","cinematic-cta"],"responsive_breakpoints":[360,768,1024,1440]}'::jsonb,'{"schema":["Organization","ProfessionalService"],"indexable":true,"content_policy":"verified-facts-only"}'::jsonb,array['cms','media','seo_core','analytics_core','security','help']::text[],'نسخه نخست قالب افق پویا با جایگزین ایمن','Initial Dynamic Horizon release with a safe fallback',now()
from public.template_catalog where key='rava-service-horizon'
on conflict(template_id,version) do update set theme_defaults=excluded.theme_defaults,layout_blueprint=excluded.layout_blueprint,seo_defaults=excluded.seo_defaults,module_defaults=excluded.module_defaults,changelog_fa=excluded.changelog_fa,changelog_en=excluded.changelog_en;

insert into public.starter_pack_template_compatibility(starter_pack_version_id,template_version_id,recommended_modules,is_default,active)
select spv.id,tv.id,array['cms','media','seo_core','analytics_core','security','help']::text[],false,true
from public.starter_content_pack_versions spv join public.starter_content_packs sp on sp.id=spv.starter_pack_id and sp.key='services.digital-agency.rava-team' join public.template_catalog tc on tc.key='rava-service-horizon' join public.template_versions tv on tv.template_id=tc.id and tv.version=1 and tv.status='published'
where spv.version=1 and spv.status='published'
on conflict(starter_pack_version_id,template_version_id) do update set active=true,recommended_modules=excluded.recommended_modules;

update public.help_translations set body_markdown=body_markdown||E'\n\nقالب «افق پویا راوا» یک قالب حرفه‌ای با حرکت پس‌زمینه کنترل‌شده است. در حالت کاهش حرکت یا نبود پشتیبانی گرافیکی، جایگزین ثابت آن خودکار نمایش داده می‌شود. انتخاب قالب فقط یک پیش‌نویس قابل بازبینی می‌سازد.',version=version+1 where locale='fa' and topic_id=(select id from public.help_topics where key='platform.design.manage');
update public.help_translations set body_markdown=body_markdown||E'\n\n“RAVA Dynamic Horizon” is a premium template with controlled ambient motion. Its static fallback is automatic when reduced motion is preferred or WebGL is unavailable. Selecting it creates a reviewable draft only.',version=version+1 where locale='en' and topic_id=(select id from public.help_topics where key='platform.design.manage');
