insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('procurement.overview','تأمین و خرید حرفه‌ای','مدیریت تأمین‌کننده، سفارش خرید، دریافت محموله، قیمت خرید و مرجوعی به تأمین‌کننده از این بخش انجام می‌شود.','این قابلیت فقط با قرارداد Procurement Pro فعال است.','Procurement Pro','Manage suppliers, purchase orders, goods receipts, purchase cost and supplier returns here.','This area requires the Procurement Pro entitlement.',true),
('procurement.suppliers','تأمین‌کننده‌ها','اطلاعات تماس، شرایط پرداخت و وضعیت هر تأمین‌کننده را ثبت و مدیریت کن.',null,'Suppliers','Manage supplier contact details, payment terms and status.',null,true),
('procurement.purchase_orders','سفارش خرید','برای هر خرید از تأمین‌کننده یک PO بساز تا تعداد، قیمت، مقصد و وضعیت دریافت قابل پیگیری باشد.','قبل از ارسال سفارش خرید، تعداد، قیمت و تأمین‌کننده را دوباره بررسی کن.','Purchase orders','Create a PO for each supplier purchase so quantities, cost, destination and receiving state stay traceable.','Recheck supplier, quantities and costs before submitting a PO.',true),
('procurement.receipts','دریافت محموله','محموله می‌تواند مرحله‌ای دریافت شود. تعداد سالم، آسیب‌دیده و کسری جدا ثبت می‌شوند.','دریافت محموله موجودی و بهای تمام‌شده را تغییر می‌دهد و باید فقط از عملیات امن سرور انجام شود.','Goods receipts','Shipments can be received partially. Accepted, damaged and shortage quantities are recorded separately.','Receiving changes inventory and cost basis and must run only through trusted server operations.',true),
('procurement.returns','مرجوعی به تأمین‌کننده','کالای معیوب یا قابل برگشت را با دلیل و تعداد مشخص به تأمین‌کننده مرجوع کن.','مرجوعی موجودی را تغییر می‌دهد و باید ثبت رویداد داشته باشد.','Supplier returns','Return damaged or eligible goods to a supplier with quantity and reason.','Supplier returns change inventory and require audit logging.',true),
('procurement.costing','قیمت خرید و سود واقعی','قیمت خرید هر محموله به‌صورت Cost Layer نگهداری می‌شود. هنگام فروش، بهای همان لحظه روی سفارش Snapshot می‌شود تا تغییر قیمت آینده سود تاریخی را عوض نکند.',null,'Costing and realized profit','Each receipt creates a cost layer. At sale time the cost basis is snapshotted onto the order so future supplier price changes cannot rewrite historical profit.',null,true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;

insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('procurement.pro.guide','commerce','/admin/commerce/procurement','راهنمای تأمین و خرید RAVA','از تأمین‌کننده تا ورود محموله و سود واقعی','۱) تأمین‌کننده را ثبت کن. ۲) برای خرید یک Purchase Order بساز. ۳) محموله را کامل یا مرحله‌ای دریافت کن و تعداد سالم، آسیب‌دیده و کسری را جدا ثبت کن. ۴) ورود سالم به انبار و Stock Ledger متصل می‌شود. ۵) قیمت خرید هر سری به‌صورت Cost Layer باقی می‌ماند. ۶) هنگام فروش، بهای تمام‌شده همان لحظه روی Order Item ذخیره می‌شود تا گزارش سود واقعی قابل اتکا بماند. ۷) مرجوعی به تأمین‌کننده هم باید به انبار و تاریخچه موجودی متصل باشد.','RAVA Procurement Guide','From suppliers to receipts and realized profit','1) Register the supplier. 2) Create a purchase order. 3) Receive shipments fully or partially and separate accepted, damaged and shortage quantities. 4) Accepted goods feed Inventory and the stock ledger. 5) Each batch keeps its own cost layer. 6) Sale-time cost basis is snapshotted onto the order item so realized profit stays historically correct. 7) Supplier returns also connect back to inventory and audit history.',array['تأمین کننده','سفارش خرید','محموله','قیمت خرید','سود','supplier','purchase order','receipt','cost','profit'],'important',array['procurement.overview','procurement.suppliers','procurement.purchase_orders','procurement.receipts','procurement.returns','procurement.costing'],true,40)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;