insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('home.media.hero','رسانه Hero','برای Hero می‌توان تصویر یا ویدیو انتخاب کرد. ویدیو اولویت دارد و Poster برای نمایش قبل از لود ویدیو استفاده می‌شود. اگر هیچ رسانه‌ای انتخاب نشود، Visual پیش‌فرض Theme نمایش داده می‌شود.',null,'Hero media','Choose an image or video for the hero. Video takes priority and the poster is shown before video playback. If no media is selected, the theme fallback visual remains active.',null,true),
('home.media.about','تصویر About','یک تصویر مکمل برای بخش درباره انتخاب کن. تصویر باید با هویت برند هماهنگ باشد و در موبایل به شکل Responsive نمایش داده می‌شود.',null,'About media','Choose a supporting About image aligned with the brand identity. It renders responsively on smaller screens.',null,true),
('home.media.cta','پس‌زمینه CTA','تصویر انتخاب‌شده با لایه تاریک محافظ روی CTA استفاده می‌شود تا خوانایی متن حفظ شود.',null,'CTA background','The selected image is rendered behind a protective dark overlay to preserve text readability.',null,true),
('home.brand.assets','لوگو و Favicon','لوگو در Header و Favicon در Metadata مرورگر استفاده می‌شوند. فایل‌های واضح و سبک انتخاب کن. تغییرات تا Publish عمومی نمی‌شوند.',null,'Logo and favicon','The logo is used in the header and the favicon in browser metadata. Choose clear, lightweight assets. Changes remain draft until published.',null,true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;

insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('home.media.workflow','content','/admin/home','راهنمای رسانه‌های صفحه اصلی','Hero، About، CTA، Logo و Favicon را از کتابخانه رسانه مدیریت کن.','برای Hero می‌توان تصویر یا ویدیو انتخاب کرد؛ در صورت استفاده از ویدیو Poster هم اضافه کن. تصویر About و CTA را متناسب با فضای Theme انتخاب کن. Logo و Favicon باید واضح و سبک باشند. تمام انتخاب‌ها ابتدا Draft هستند؛ Preview واقعی را بررسی کن و سپس Publish بزن.','Homepage media workflow','Manage Hero, About, CTA, logo and favicon through the tenant media library.','Hero supports image or video; add a poster when using video. Choose About and CTA media that suit the active theme. Keep logo and favicon clear and lightweight. All changes remain draft until you verify the real preview and publish.',array['hero','video','poster','logo','favicon','about','cta','رسانه','لوگو'], 'important',array['home.media.hero','home.media.about','home.media.cta','home.brand.assets','home.publish'],true,22)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;
