insert into public.admin_help_items(help_key,title_fa,body_fa,title_en,body_en,warning_fa,warning_en) values
('projects.slug','آدرس پروژه چیست؟','Slug بخش پایانی آدرس صفحه پروژه است. فقط از حروف کوچک انگلیسی، عدد و خط تیره استفاده کنید؛ مثل rava-website.','What is a project slug?','The slug is the final part of the project URL. Use lowercase English letters, numbers and hyphens only, for example rava-website.',null,null),
('projects.category','دسته‌بندی پروژه','برای گروه‌بندی و فیلتر نمونه‌کارها استفاده می‌شود. نام‌های کوتاه و ثابت انتخاب کنید.','Project category','Used to group and filter portfolio items. Prefer short, consistent category names.',null,null),
('projects.schedule','انتشار زمان‌بندی‌شده','وقتی وضعیت روی زمان‌بندی‌شده است، این زمان مشخص می‌کند پروژه چه زمانی آماده انتشار باشد.','Scheduled publishing','When status is Scheduled, this time defines when the project is intended to become publishable.',null,null),
('projects.featured','پروژه ویژه','پروژه‌های مهم را برای نمایش برجسته در بخش‌های منتخب سایت علامت‌گذاری می‌کند.','Featured project','Marks important projects for highlighted placement in selected areas of the website.',null,null),
('projects.services','خدمات انجام‌شده','هر خدمت را در یک خط بنویسید تا در صفحه پروژه به‌صورت ساختاریافته نمایش داده شود.','Project services','Enter one service per line so services can be displayed as structured project information.',null,null),
('projects.media','رسانه پروژه','کاور تصویر اصلی پروژه است. گالری می‌تواند چند تصویر داشته باشد و ترتیب آن‌ها قابل تغییر است.','Project media','The cover is the project’s primary image. The gallery can contain multiple images in a controlled order.',null,null),
('seo.basics','راهنمای SEO','عنوان SEO و Meta Description برای معرفی بهتر صفحه به موتور جستجو استفاده می‌شوند. متن باید دقیق، طبیعی و مرتبط با همان صفحه باشد.','SEO basics','SEO title and meta description help describe the page to search engines. Keep them accurate, natural and specific to the page.',null,null),
('media.upload','آپلود فایل','فایل را در پوشه مناسب آپلود کنید و بعد از آپلود اطلاعات آن مثل عنوان و Alt را تکمیل کنید.','Upload media','Upload the file into an appropriate folder, then complete metadata such as title and alt text.',null,null),
('media.folder','پوشه رسانه','پوشه‌ها برای نظم Media Library هستند و جابه‌جایی فایل بین آن‌ها آدرس فایل را به‌تنهایی تغییر نمی‌دهد.','Media folder','Folders organize the Media Library. Moving an asset between virtual folders does not by itself change its file URL.',null,null),
('media.delete','حذف رسانه','حذف عادی فایل را ابتدا به سطل زباله می‌فرستد تا امکان بازیابی وجود داشته باشد.','Delete media','Normal deletion first moves the asset to Trash so it can be restored.','حذف دائمی قابل بازیابی نیست.','Permanent deletion cannot be undone.'),
('logs.search','جستجوی لاگ','می‌توانید با شماره عددی، Log ID، Request ID، مسیر، نوع رویداد یا متن فارسی خطا جستجو کنید.','Search logs','Search by numeric ID, Log ID, Request ID, route, event type or error text.',null,null),
('users.sessions','نشست‌های فعال','نشست یعنی ورود فعال یک مدیر. بستن نشست‌ها کاربر را مجبور می‌کند دوباره وارد شود.','Active sessions','A session represents an active administrator login. Revoking sessions requires the user to sign in again.','بستن همه نشست‌ها ممکن است کاربر را از تمام دستگاه‌ها خارج کند.','Revoking all sessions may sign the user out on every device.'),
('security.permissions','دسترسی مدیریتی','فقط دسترسی لازم را به هر مدیر بدهید. تغییر دسترسی‌ها در Audit Log ثبت می‌شود.','Admin permissions','Grant only the permissions each administrator needs. Permission changes are recorded in the audit log.','اصل حداقل دسترسی را رعایت کنید.','Follow the principle of least privilege.')
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_fa=excluded.warning_fa,warning_en=excluded.warning_en,updated_at=now();
