insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('experience.overview','Page Experience چیست؟','Theme هویت کلی برند مثل رنگ، فونت و زبان بصری را نگه می‌دارد. Page Experience فقط چیدمان و رفتار همان صفحه را تخصصی می‌کند؛ مثلاً یک صفحه خدمات، محصول یا Landing می‌تواند تجربه متفاوتی داشته باشد بدون اینکه هویت سایت عوض شود.',null,'What is Page Experience?','The Theme keeps global brand identity such as color, typography and visual language. Page Experience only specializes the composition and behavior of one page, such as service, product or landing pages, without replacing the site identity.',null,true),
('experience.page_type','نوع صفحه','نوع صفحه نقش محتوایی آن را مشخص می‌کند و تعیین می‌کند چه Experience Packهایی مناسب هستند. ابتدا نوع درست را انتخاب کن و بعد Pack متناسب را انتخاب کن.',null,'Page type','Page type describes the semantic role of the page and determines which Experience Packs are compatible. Choose the correct type first, then select a matching pack.',null,true),
('experience.pack','Experience Pack','Experience Pack یک طراحی تخصصی برای همان نوع صفحه است. بعضی Packها عمومی‌اند و بعضی به قابلیت خریداری‌شده مثل Commerce نیاز دارند. انتخاب Pack هویت اصلی Theme را تغییر نمی‌دهد.','Packهای قفل‌شده فقط از طریق قرارداد و Entitlement مرکزی فعال می‌شوند.','Experience Pack','An Experience Pack is specialized page-level presentation. Some packs are general and others require a purchased capability such as Commerce. Selecting a pack does not replace the global Theme.','Locked packs are enabled only through central contract entitlements.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;

insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('experience.composable-pages','appearance','/admin/pages','ترکیب تجربه‌های مختلف در یک سایت','چطور یک سایت خدماتی، فروشگاهی، محتوایی و کمپینی را بدون قاطی‌کردن Themeها بسازیم','در RAVA قالب اصلی سایت فقط هویت برند را مشخص می‌کند. برای هر صفحه ابتدا Page Type را انتخاب کن؛ مثلاً Service، Product، Collection، Article یا Landing. سپس Experience Pack متناسب را انتخاب کن. صفحه محصول می‌تواند Commerce Premium باشد، در حالی که Home و Services همچنان ظاهر Creative یا Agency داشته باشند. Packهای تجاری تنها زمانی قابل استفاده‌اند که قابلیت مرتبط در قرارداد مشتری فعال باشد. اگر هیچ Pack انتخاب نکنی، صفحه از طراحی عمومی Theme استفاده می‌کند.','Composable page experiences','Mix service, commerce, editorial and campaign experiences without mixing global themes','RAVA keeps one global Theme for brand identity. Each page can then choose a semantic Page Type and a compatible Experience Pack. A product page may use Commerce Premium while Home and Services keep a creative agency identity. Commercial packs require the matching tenant entitlement. Selecting no pack falls back to the global Theme presentation.',array['page experience','experience pack','صفحه محصول','لندینگ','ترکیب قالب','commerce','service'], 'important',array['experience.overview','experience.page_type','experience.pack'],true,18)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;
