-- Promotion Engine V1. Designed for code + automatic promotions, targeting, scheduling, usage limits and explicit stacking rules.
create table if not exists public.promotions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,name text not null,code text,trigger_type text not null default 'code' check(trigger_type in('code','automatic')),discount_type text not null check(discount_type in('percentage','fixed_amount','free_shipping','buy_x_get_y')),value numeric(18,4) not null default 0 check(value>=0),status text not null default 'draft' check(status in('draft','active','paused','expired','archived')),starts_at timestamptz,ends_at timestamptz,min_subtotal bigint,min_quantity int,max_discount_amount bigint,usage_limit_total int,usage_limit_per_customer int,priority int not null default 100,stacking_group text not null default 'default',stacking_mode text not null default 'exclusive' check(stacking_mode in('exclusive','best_price','stackable')),customer_scope text not null default 'all' check(customer_scope in('all','specific_customers','segments')),market_scope jsonb not null default '[]'::jsonb,conditions jsonb not null default '{}'::jsonb,reward_config jsonb not null default '{}'::jsonb,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at is null or starts_at is null or ends_at>starts_at),unique(tenant_id,code));
create table if not exists public.promotion_targets(id uuid primary key default gen_random_uuid(),promotion_id uuid not null references public.promotions(id) on delete cascade,target_type text not null check(target_type in('all_products','product','category')),target_id uuid,excluded boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.promotion_redemptions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,promotion_id uuid not null references public.promotions(id) on delete restrict,order_id uuid references public.orders(id) on delete set null,customer_key text,discount_amount bigint not null default 0 check(discount_amount>=0),created_at timestamptz not null default now());
create table if not exists public.order_discounts(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,promotion_id uuid references public.promotions(id) on delete set null,promotion_name text not null,code text,discount_type text not null,amount bigint not null check(amount>=0),metadata jsonb not null default '{}'::jsonb);
create index if not exists promotions_active_idx on public.promotions(tenant_id,status,starts_at,ends_at,priority);create index if not exists promotion_redemptions_lookup_idx on public.promotion_redemptions(tenant_id,promotion_id,customer_key);
alter table public.promotions enable row level security;alter table public.promotion_targets enable row level security;alter table public.promotion_redemptions enable row level security;alter table public.order_discounts enable row level security;
create policy promotions_tenant_all on public.promotions for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));
create policy promotion_targets_tenant_all on public.promotion_targets for all to authenticated using(exists(select 1 from public.promotions p where p.id=promotion_id and public.can_access_tenant(p.tenant_id,null))) with check(exists(select 1 from public.promotions p where p.id=promotion_id and public.can_access_tenant(p.tenant_id,null)));
create policy promotion_redemptions_tenant_read on public.promotion_redemptions for select to authenticated using(public.can_access_tenant(tenant_id,null));
create policy order_discounts_tenant_read on public.order_discounts for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and public.can_access_tenant(o.tenant_id,null)));
-- Checkout must calculate promotions server-side from current product prices and persist an immutable order_discounts snapshot. Never trust discount totals sent by the browser.
