-- RAVA Shipping Pro: optional contractual add-on. Checkout must ignore these tables unless shipping.pro is entitled.
create table if not exists public.shipping_settings(id uuid primary key default gen_random_uuid(),tenant_id uuid not null unique references public.tenants(id) on delete cascade,enabled boolean not null default false,origin_country text,origin_region text,default_currency text not null default 'IRR',free_shipping_threshold numeric(18,4),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.shipping_methods(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,name_fa text not null,name_en text not null default '',code text not null,enabled boolean not null default true,pricing_type text not null default 'flat' check(pricing_type in('flat','free','order_amount','weight')),base_price numeric(18,4) not null default 0 check(base_price>=0),currency text not null,free_over numeric(18,4),min_order numeric(18,4),max_order numeric(18,4),estimated_min_days int,estimated_max_days int,sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code),check(estimated_min_days is null or estimated_min_days>=0),check(estimated_max_days is null or estimated_max_days>=coalesce(estimated_min_days,0)));
create table if not exists public.shipping_zones(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,name text not null,countries text[] not null default '{}',regions text[] not null default '{}',postal_prefixes text[] not null default '{}',priority int not null default 100,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.shipping_method_zones(method_id uuid not null references public.shipping_methods(id) on delete cascade,zone_id uuid not null references public.shipping_zones(id) on delete cascade,tenant_id uuid not null references public.tenants(id) on delete cascade,primary key(method_id,zone_id));
create index if not exists shipping_methods_tenant_idx on public.shipping_methods(tenant_id,enabled,sort_order);create index if not exists shipping_zones_tenant_idx on public.shipping_zones(tenant_id,enabled,priority);
alter table public.shipping_settings enable row level security;alter table public.shipping_methods enable row level security;alter table public.shipping_zones enable row level security;alter table public.shipping_method_zones enable row level security;
create policy shipping_settings_admin on public.shipping_settings for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));create policy shipping_methods_admin on public.shipping_methods for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));create policy shipping_zones_admin on public.shipping_zones for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));create policy shipping_method_zones_admin on public.shipping_method_zones for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));
-- Browser checkout never supplies a trusted shipping price. A server-side shipping quote/commit function will calculate and persist it from enabled methods/zones.
