insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('sections.overview','Section Builder','هر صفحه از سکشن‌های مستقل ساخته می‌شود. سکشن‌ها می‌توانند Variant متفاوت، محتوای جدا، وضعیت نمایش مستقل و تنظیمات Responsive داشته باشند. تمام تغییرات ابتدا Draft هستند.','برای اعمال تغییر روی سایت عمومی باید Publish Sections انجام شود.','Section Builder','Each page is composed from independent sections with variants, content, visibility and responsive controls. Changes are saved as Draft first.','Use Publish Sections to update the public page.',true),
('sections.variant','Variant سکشن','Variant فقط نحوه نمایش همان سکشن را عوض می‌کند و Theme اصلی سایت را تغییر نمی‌دهد. Variantها از Registry کنترل می‌شوند تا طراحی ناسازگار وارد صفحه نشود.',null,'Section variant','A variant changes only the presentation of this section and does not replace the site theme. Variants are registry-controlled for design consistency.',null,true),
('sections.responsive','نمایش در دستگاه‌ها','می‌توانی مشخص کنی سکشن در Desktop، Tablet یا Mobile دیده شود. این تنظیم در Draft ذخیره می‌شود و بعد از Publish اعمال خواهد شد.','اگر هر سه گزینه خاموش باشند سکشن در هیچ دستگاهی نمایش داده نمی‌شود.','Responsive visibility','Choose whether the section is visible on desktop, tablet or mobile. The setting is drafted first and applied after publish.','If all devices are disabled, the section will not appear anywhere.',true),
('sections.publish','انتشار سکشن‌ها','Publish Sections تمام محتوای Draft، Variant، وضعیت نمایش، تنظیمات Responsive و حذف‌های Draft را یکجا به نسخه عمومی منتقل می‌کند.','قبل از انتشار Preview Draft را بررسی کن. قابلیت‌های قراردادی موردنیاز دوباره روی سرور کنترل می‌شوند.','Publish sections','Publish Sections promotes all draft content, variants, visibility, responsive settings and draft removals to the public version.','Review Draft Preview first. Required commercial entitlements are validated again on the server.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;

insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('sections.builder.workflow','content','/admin/pages','ساخت صفحه با Section Builder','از اضافه‌کردن سکشن تا Preview و Publish','۱) Page Type و Experience صفحه را انتخاب کن. ۲) فقط سکشن‌های سازگار با همان نوع صفحه نمایش داده می‌شوند. ۳) سکشن را اضافه کن و Variant مناسب را انتخاب کن. ۴) محتوای Draft و نمایش Desktop/Tablet/Mobile را تنظیم کن. ۵) ترتیب سکشن‌ها را تغییر بده یا سکشن را در Draft مخفی/حذف کن. ۶) Preview Draft را بررسی کن. ۷) در پایان Publish Sections را بزن. هیچ تغییر Draft قبل از Publish روی نسخه عمومی اعمال نمی‌شود. سکشن‌های پولی فقط در صورت فعال بودن قرارداد مشتری قابل انتشارند.','Building pages with Section Builder','From adding sections to preview and publish','1) Choose the page type and Experience. 2) Only compatible sections are offered. 3) Add a section and choose a variant. 4) Edit draft content and desktop/tablet/mobile visibility. 5) Reorder, hide or mark sections for removal in Draft. 6) Review Draft Preview. 7) Use Publish Sections. Draft changes never reach the public page before publish, and paid sections require an active entitlement.',array['section','سکشن','page builder','variant','responsive','draft','publish','صفحه ساز'], 'important',array['sections.overview','sections.variant','sections.responsive','sections.publish'],true,18)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;
