-- RAVA Payment Engine V1. Gateway credentials are never stored in public/client-readable tables.
create table if not exists public.payment_gateway_configs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,provider_key text not null,display_name text not null,enabled boolean not null default false,test_mode boolean not null default true,public_config jsonb not null default '{}'::jsonb,secret_ref text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,provider_key));
create table if not exists public.payment_transactions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,order_id uuid not null references public.orders(id) on delete restrict,gateway_config_id uuid references public.payment_gateway_configs(id) on delete set null,provider_key text not null,attempt_no int not null default 1 check(attempt_no>0),amount bigint not null check(amount>=0),currency text not null,status text not null default 'created' check(status in('created','redirected','callback_received','verifying','paid','failed','cancelled','expired','refunded','partially_refunded')),idempotency_key text not null,provider_authority text,provider_reference text,provider_status text,request_fingerprint text,callback_fingerprint text,failure_code text,failure_message text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),verified_at timestamptz,unique(tenant_id,idempotency_key),unique(provider_key,provider_reference));
create table if not exists public.payment_events(id bigint generated always as identity primary key,tenant_id uuid not null references public.tenants(id) on delete restrict,transaction_id uuid not null references public.payment_transactions(id) on delete cascade,event_type text not null,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists payment_tx_order_idx on public.payment_transactions(tenant_id,order_id,created_at desc);create index if not exists payment_tx_status_idx on public.payment_transactions(tenant_id,status,created_at desc);create index if not exists payment_events_tx_idx on public.payment_events(transaction_id,created_at);
alter table public.payment_gateway_configs enable row level security;alter table public.payment_transactions enable row level security;alter table public.payment_events enable row level security;
create policy payment_gateway_configs_admin_read on public.payment_gateway_configs for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy payment_transactions_admin_read on public.payment_transactions for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy payment_events_admin_read on public.payment_events for select to authenticated using(public.can_access_tenant(tenant_id,null));
-- No direct browser write policies. Payment creation, callbacks, verification, refunds and status changes must pass through trusted server code.
-- Paid must only be set after server-to-server verification with the configured provider. Callback parameters alone are never proof of payment.
