insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('home.content','مدیریت صفحه اصلی','این بخش متن‌ها و اطلاعات صفحه اصلی را جدا از قالب مدیریت می‌کند. ابتدا Draft را ذخیره کن و پس از بررسی Publish بزن.',null,'Homepage content','Manage homepage copy and business information separately from the theme. Save a draft first, then publish after review.',null,true),
('home.hero','Hero صفحه اصلی','تیتر، متن معرفی و CTAهای بالای صفحه را اینجا ویرایش کن. لینک‌ها فقط مسیر داخلی، https، ایمیل یا تلفن معتبر را می‌پذیرند.',null,'Homepage hero','Edit the main headline, intro and calls to action. Links accept safe internal, HTTPS, email or telephone destinations.',null,true),
('home.services','خدمات صفحه اصلی','خدماتی را وارد کن که برای تصمیم مشتری مهم‌ترند. عنوان کوتاه و توضیح واضح معمولاً بهتر از متن طولانی عمل می‌کند.',null,'Homepage services','Show the services most useful for customer decisions. Short titles and clear descriptions usually work best.',null,true),
('home.footer','تماس و اطلاعات کسب‌وکار','اطلاعات تماس، موقعیت، شبکه‌ها و مشخصات مجوز یا کسب‌وکار در Footer نمایش داده می‌شوند. قبل از انتشار صحت اطلاعات رسمی را بررسی کن.','اطلاعات مجوز و تماس عمومی هستند.','Contact and business information','Contact, location, social links and license/business details appear in the footer. Verify official information before publishing.','License and contact information become public.',true),
('home.publish','انتشار صفحه اصلی','Publish آخرین Draft ذخیره‌شده را برای بازدیدکنندگان عمومی می‌کند و نسخه قبلی در Revision نگهداری می‌شود.','قبل از تأیید، متن، لینک و اطلاعات تماس را بررسی کن.','Publish homepage','Publish makes the latest saved draft public and keeps the prior version in revision history.','Review copy, links and contact details before confirming.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;
insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('home.content.workflow','content','/admin/home','ویرایش صفحه اصلی بدون دست‌زدن به قالب','از Hero تا Footer را با Draft و Publish امن مدیریت کن.','۱) متن Hero و دکمه‌ها را اصلاح کن. ۲) خدمات اصلی را مرتب و واضح بنویس. ۳) About و معرفی مدیر/تیم را تنظیم کن. ۴) اطلاعات تماس و مجوز را بررسی کن. ۵) Draft را ذخیره کن. ۶) پس از بررسی، Publish بزن. تغییر ظاهر سایت از Theme Studio انجام می‌شود و محتوای این صفحه با تعویض Theme از بین نمی‌رود.','Edit homepage without changing the theme','Manage Hero through Footer with a safe draft and publish workflow.','1) Update hero copy and CTAs. 2) Keep services clear and useful. 3) Configure about/team content. 4) Verify contact and license details. 5) Save draft. 6) Publish after review. Visual design belongs to Theme Studio, so switching themes does not delete homepage content.',array['صفحه اصلی','hero','services','footer','contact','home','homepage','publish','draft'],'important',array['home.content','home.hero','home.services','home.footer','home.publish'],true,21)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;
