-- Wishlist + Back-in-stock alerts, bound to the real Product/Variant model.
create table if not exists public.customer_wishlist_items(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,
 product_id uuid not null references public.products(id) on delete cascade,variant_id uuid references public.product_variants(id) on delete cascade,
 created_at timestamptz not null default now(),unique(tenant_id,user_id,product_id,variant_id)
);
-- PostgreSQL unique constraints permit multiple NULLs; prevent duplicate product-level wishlist rows too.
create unique index if not exists customer_wishlist_product_only_uq on public.customer_wishlist_items(tenant_id,user_id,product_id) where variant_id is null;
create table if not exists public.back_in_stock_subscriptions(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,
 product_id uuid not null references public.products(id) on delete cascade,variant_id uuid not null references public.product_variants(id) on delete cascade,
 active boolean not null default true,last_notified_at timestamptz,last_available_quantity bigint,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(tenant_id,user_id,variant_id)
);
alter table public.customer_wishlist_items enable row level security;alter table public.back_in_stock_subscriptions enable row level security;
create policy wishlist_self_select on public.customer_wishlist_items for select to authenticated using(user_id=auth.uid());
create policy back_in_stock_self_select on public.back_in_stock_subscriptions for select to authenticated using(user_id=auth.uid());
-- Writes go through validated RPCs only; do not expose raw inserts/updates/deletes to customer sessions.

create or replace function public.toggle_customer_wishlist(p_tenant uuid,p_product uuid,p_variant uuid default null) returns boolean language plpgsql security definer set search_path=public as $$declare exists_row uuid;begin if auth.uid() is null then raise exception 'authentication_required';end if;if not exists(select 1 from public.customer_profiles where tenant_id=p_tenant and user_id=auth.uid()) then raise exception 'customer_profile_required';end if;if not exists(select 1 from public.products p where p.id=p_product and p.tenant_id=p_tenant and p.status='active') then raise exception 'product_not_available';end if;if p_variant is not null and not exists(select 1 from public.product_variants v where v.id=p_variant and v.product_id=p_product and v.tenant_id=p_tenant) then raise exception 'variant_mismatch';end if;select id into exists_row from public.customer_wishlist_items where tenant_id=p_tenant and user_id=auth.uid() and product_id=p_product and variant_id is not distinct from p_variant;if exists_row is not null then delete from public.customer_wishlist_items where id=exists_row;return false;end if;insert into public.customer_wishlist_items(tenant_id,user_id,product_id,variant_id) values(p_tenant,auth.uid(),p_product,p_variant);return true;end$$;
revoke all on function public.toggle_customer_wishlist(uuid,uuid,uuid) from public;grant execute on function public.toggle_customer_wishlist(uuid,uuid,uuid) to authenticated;

create or replace function public.set_back_in_stock_subscription(p_tenant uuid,p_variant uuid,p_active boolean) returns boolean language plpgsql security definer set search_path=public as $$declare p uuid;begin if auth.uid() is null then raise exception 'authentication_required';end if;if not exists(select 1 from public.customer_profiles where tenant_id=p_tenant and user_id=auth.uid()) then raise exception 'customer_profile_required';end if;select product_id into p from public.product_variants where id=p_variant and tenant_id=p_tenant;if p is null then raise exception 'variant_not_found';end if;insert into public.back_in_stock_subscriptions(tenant_id,user_id,product_id,variant_id,active,updated_at) values(p_tenant,auth.uid(),p,p_variant,p_active,now()) on conflict(tenant_id,user_id,variant_id) do update set active=excluded.active,updated_at=now();return p_active;end$$;
revoke all on function public.set_back_in_stock_subscription(uuid,uuid,boolean) from public;grant execute on function public.set_back_in_stock_subscription(uuid,uuid,boolean) to authenticated;

-- Customer-safe read model. Product tables keep their stricter admin RLS; this RPC returns only the customer's own saved active catalog rows.
create or replace function public.customer_wishlist_view(p_tenant uuid) returns jsonb language sql security definer set search_path=public as $$
 select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'product_id',p.id,'product_name',p.name,'product_slug',p.slug,'product_status',p.status,'variant_id',v.id,'variant_title',v.title,'sku',v.sku,'price',v.price,'currency',v.currency,'track_inventory',v.track_inventory,'inventory_quantity',v.inventory_quantity,'alert_active',coalesce(a.active,false),'last_notified_at',a.last_notified_at,'created_at',w.created_at) order by w.created_at desc),'[]'::jsonb)
 from public.customer_wishlist_items w join public.products p on p.id=w.product_id and p.tenant_id=w.tenant_id left join public.product_variants v on v.id=w.variant_id and v.tenant_id=w.tenant_id left join public.back_in_stock_subscriptions a on a.tenant_id=w.tenant_id and a.user_id=w.user_id and a.variant_id=w.variant_id where w.tenant_id=p_tenant and w.user_id=auth.uid()
$$;
revoke all on function public.customer_wishlist_view(uuid) from public;grant execute on function public.customer_wishlist_view(uuid) to authenticated;

-- Existing Notification Pro tenants gain the event rule without overwriting their other choices.
update public.notification_settings set event_rules=jsonb_set(event_rules,'{inventory.back_in_stock}','true'::jsonb,true),updated_at=now() where not(event_rules ? 'inventory.back_in_stock');

create or replace function public.enqueue_back_in_stock_for_variant(p_tenant uuid,p_variant uuid,p_available bigint) returns integer language plpgsql security definer set search_path=public as $$declare r record;profile public.customer_profiles;s public.notification_settings;prefs public.customer_notification_preferences;ch text;recipient text;loc text;n int:=0;idem text;channel_allowed boolean;begin if p_available<=0 then return 0;end if;if not public.has_entitlement(p_tenant,'notifications.pro') then return 0;end if;select * into s from public.notification_settings where tenant_id=p_tenant;if not found or not s.enabled then return 0;end if;if not coalesce((s.event_rules->>'inventory.back_in_stock')::boolean,true) then return 0;end if;for r in select * from public.back_in_stock_subscriptions where tenant_id=p_tenant and variant_id=p_variant and active=true and (last_available_quantity is null or last_available_quantity<=0 or last_notified_at is null) loop select * into profile from public.customer_profiles where tenant_id=p_tenant and user_id=r.user_id;if not found then continue;end if;select * into prefs from public.customer_notification_preferences where tenant_id=p_tenant and user_id=r.user_id;loc:=coalesce(profile.locale,s.default_locale,'fa');foreach ch in array array['email','sms','whatsapp','push'] loop channel_allowed:=case ch when 'email' then coalesce(prefs.transactional_email,true) when 'sms' then coalesce(prefs.transactional_sms,true) when 'whatsapp' then coalesce(prefs.transactional_whatsapp,false) when 'push' then coalesce(prefs.transactional_push,false) else false end;if coalesce((s.channels->>ch)::boolean,false) and channel_allowed then recipient:=case when ch='email' then nullif(profile.email,'') when ch in('sms','whatsapp') then nullif(profile.phone,'') else null end;if recipient is not null then idem:=encode(digest(p_tenant::text||':back_in_stock:'||r.id::text||':'||p_available::text||':'||ch,'sha256'),'hex');insert into public.notification_outbox(tenant_id,event_key,entity_type,entity_id,customer_id,channel,recipient,locale,payload,idempotency_key) values(p_tenant,'inventory.back_in_stock','variant',p_variant,profile.id,ch,recipient,loc,jsonb_build_object('variant_id',p_variant,'product_id',r.product_id,'available_quantity',p_available),idem) on conflict(tenant_id,idempotency_key) do nothing;if found then n:=n+1;end if;end if;end if;end loop;update public.back_in_stock_subscriptions set last_notified_at=now(),last_available_quantity=p_available,updated_at=now() where id=r.id;end loop;return n;end$$;
revoke all on function public.enqueue_back_in_stock_for_variant(uuid,uuid,bigint) from public,anon,authenticated;grant execute on function public.enqueue_back_in_stock_for_variant(uuid,uuid,bigint) to service_role;

-- Inventory Pro: sellable stock is on_hand - reserved at a location.
create or replace function public.back_in_stock_inventory_trigger() returns trigger language plpgsql security definer set search_path=public as $$declare before_available bigint:=0;after_available bigint:=0;begin if new.variant_id is null then return new;end if;if tg_op='UPDATE' then before_available:=coalesce(old.on_hand-old.reserved,0);end if;after_available:=coalesce(new.on_hand-new.reserved,0);if before_available<=0 and after_available>0 then perform public.enqueue_back_in_stock_for_variant(new.tenant_id,new.variant_id,after_available);elsif after_available<=0 then update public.back_in_stock_subscriptions set last_available_quantity=after_available,updated_at=now() where tenant_id=new.tenant_id and variant_id=new.variant_id and active=true;end if;return new;end$$;
drop trigger if exists trg_back_in_stock_inventory on public.inventory_balances;create trigger trg_back_in_stock_inventory after insert or update of on_hand,reserved on public.inventory_balances for each row execute function public.back_in_stock_inventory_trigger();

-- Commerce Core without Inventory Pro: react to the variant's simple inventory_quantity.
create or replace function public.back_in_stock_variant_trigger() returns trigger language plpgsql security definer set search_path=public as $$declare before_available bigint:=0;after_available bigint:=0;begin if not new.track_inventory then return new;end if;if tg_op='UPDATE' then before_available:=coalesce(old.inventory_quantity,0);end if;after_available:=coalesce(new.inventory_quantity,0);if before_available<=0 and after_available>0 then perform public.enqueue_back_in_stock_for_variant(new.tenant_id,new.id,after_available);elsif after_available<=0 then update public.back_in_stock_subscriptions set last_available_quantity=after_available,updated_at=now() where tenant_id=new.tenant_id and variant_id=new.id and active=true;end if;return new;end$$;
drop trigger if exists trg_back_in_stock_variant on public.product_variants;create trigger trg_back_in_stock_variant after insert or update of inventory_quantity,track_inventory on public.product_variants for each row execute function public.back_in_stock_variant_trigger();

insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('customers.wishlist','علاقه‌مندی‌های مشتری','مشتری می‌تواند محصول یا Variant مشخص مثل رنگ/سایز را به علاقه‌مندی‌ها اضافه کند و بعداً از حساب خودش مدیریت کند.',null,'Customer wishlist','Customers can save a product or a specific variant such as a color/size and manage saved items from their account.',null,true),
('customers.back_in_stock','موجود شد خبرم کن','اشتراک موجودی روی Variant دقیق ثبت می‌شود. چه فروشگاه از موجودی ساده استفاده کند چه Inventory Pro، وقتی موجودی قابل فروش از صفر به بیشتر از صفر برسد یک اعلان تکرارناپذیر ساخته می‌شود و تنظیم کانال‌های اعلان مشتری نیز رعایت می‌شود.','اعلان فقط بعد از افزایش واقعی موجودی قابل فروش ساخته شود؛ تغییر ظاهری یا Retry نباید پیام تکراری ایجاد کند.','Back-in-stock alerts','Subscriptions target the exact variant. Whether the store uses basic stock or Inventory Pro, a zero-to-positive sellable-stock transition creates an idempotent alert while respecting the customer channel preferences.','Only a real sellable-stock transition should trigger an alert; retries or cosmetic changes must not create duplicates.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;
