-- RAVA Order Lifecycle: auditable state transitions, shipment tracking and return/refund requests.
alter table public.orders add column if not exists fulfillment_status text not null default 'unfulfilled';
alter table public.orders add column if not exists cancelled_at timestamptz;
alter table public.orders add column if not exists completed_at timestamptz;
create table if not exists public.order_status_history(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,order_id uuid not null references public.orders(id) on delete restrict,from_status text,to_status text not null,from_fulfillment_status text,to_fulfillment_status text,note text,actor_user_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create index if not exists order_status_history_order_idx on public.order_status_history(tenant_id,order_id,created_at desc);
create table if not exists public.order_shipments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,order_id uuid not null references public.orders(id) on delete restrict,shipping_method_id uuid references public.shipping_methods(id) on delete set null,carrier text,tracking_code text,tracking_url text,status text not null default 'preparing' check(status in('preparing','packed','shipped','delivered','returned','cancelled')),shipped_at timestamptz,delivered_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists order_shipments_order_idx on public.order_shipments(tenant_id,order_id,created_at desc);
create table if not exists public.order_returns(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete restrict,order_id uuid not null references public.orders(id) on delete restrict,status text not null default 'requested' check(status in('requested','approved','rejected','received','refunded','closed')),reason text,note text,refund_amount numeric(20,4) check(refund_amount is null or refund_amount>=0),currency text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.order_status_history enable row level security;alter table public.order_shipments enable row level security;alter table public.order_returns enable row level security;
create policy order_status_history_admin on public.order_status_history for select to authenticated using(public.can_access_tenant(tenant_id,null));create policy order_shipments_admin on public.order_shipments for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));create policy order_returns_admin on public.order_returns for all to authenticated using(public.can_access_tenant(tenant_id,null)) with check(public.can_access_tenant(tenant_id,null));
create or replace function public.transition_order_state(p_tenant uuid,p_order uuid,p_status text,p_fulfillment text,p_note text default null,p_actor uuid default null) returns public.orders language plpgsql security definer set search_path=public as $$declare o public.orders;old_status text;old_fulfillment text;begin if not public.can_access_tenant(p_tenant,null) then raise exception 'forbidden';end if;select * into o from public.orders where id=p_order and tenant_id=p_tenant for update;if o.id is null then raise exception 'order_not_found';end if;old_status:=o.status;old_fulfillment:=o.fulfillment_status;if p_status not in('pending','confirmed','processing','completed','cancelled') then raise exception 'invalid_order_status';end if;if p_fulfillment not in('unfulfilled','preparing','packed','shipped','delivered','returned','cancelled') then raise exception 'invalid_fulfillment_status';end if;if old_status='cancelled' and p_status<>'cancelled' then raise exception 'cancelled_order_is_terminal';end if;if old_status='completed' and p_status not in('completed') then raise exception 'completed_order_is_terminal';end if;if p_fulfillment in('shipped','delivered') and o.payment_status not in('paid','authorized') then raise exception 'cannot_ship_unpaid_order';end if;update public.orders set status=p_status,fulfillment_status=p_fulfillment,cancelled_at=case when p_status='cancelled' then coalesce(cancelled_at,now()) else cancelled_at end,completed_at=case when p_status='completed' then coalesce(completed_at,now()) else completed_at end,updated_at=now() where id=o.id returning * into o;insert into public.order_status_history(tenant_id,order_id,from_status,to_status,from_fulfillment_status,to_fulfillment_status,note,actor_user_id) values(p_tenant,p_order,old_status,p_status,old_fulfillment,p_fulfillment,left(nullif(trim(p_note),''),1000),p_actor);return o;end$$;
revoke all on function public.transition_order_state(uuid,uuid,text,text,text,uuid) from public,anon;grant execute on function public.transition_order_state(uuid,uuid,text,text,text,uuid) to authenticated;
