-- Contextual bilingual help for commercial controls. Existing guidance system owns presentation/search.
insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('platform.entitlements','مدیریت دسترسی‌های قراردادی','این صفحه مشخص می‌کند هر مشتری بر اساس قرارداد به کدام قابلیت‌های پولی دسترسی دارد. تغییرات فقط توسط Platform Owner انجام می‌شود و در Audit Log ثبت خواهد شد.','فعال‌سازی قابلیت بدون تطبیق با قرارداد می‌تواند تعهد تجاری ایجاد کند.','Contract entitlements','This page controls which paid capabilities each tenant can use. Changes are Platform Owner-only and are written to the audit log.','Grant capabilities only when they match the customer contract.',true),
('platform.entitlements.tenant','انتخاب مشتری','قبل از هر تغییر نام و شناسه مشتری را بررسی کن. تمام دسترسی‌های پایین صفحه فقط برای Tenant انتخاب‌شده هستند.',null,'Choose customer','Verify the customer before editing. All entitlements below apply only to the selected tenant.',null,true),
('platform.entitlements.status','وضعیت دسترسی','Active یعنی دسترسی عادی؛ Trial برای دوره آزمایشی؛ Expired برای قرارداد پایان‌یافته؛ Suspended برای توقف دستی دسترسی است.','Suspended و Expired می‌توانند قابلیت مشتری را فوراً غیرقابل استفاده کنند.','Entitlement status','Active grants normal access; Trial is temporary; Expired represents an ended term; Suspended manually blocks access.','Suspended and Expired can immediately block customer capability access.',true),
('platform.entitlements.limits','محدودیت قابلیت','برای قابلیت‌هایی که سقف مصرف دارند می‌توان یک کلید و مقدار محدودیت ثبت کرد؛ مثل تعداد درخواست AI در ماه. اگر محدودیت لازم نیست این فیلدها را خالی بگذار.',null,'Capability limits','Optional limits can record a quota such as monthly AI requests. Leave blank when the contract has no quota.',null,true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;

insert into public.guidance_articles(article_key,area,route_prefix,title_fa,summary_fa,body_fa,title_en,summary_en,body_en,keywords,importance,related_help_keys,active,sort_order) values
('platform.entitlements.workflow','platform','/admin/platform/entitlements','راهنمای قرارداد و دسترسی مشتری','روش امن فعال‌سازی قابلیت‌های فروخته‌شده','۱) مشتری صحیح را انتخاب کن. ۲) قابلیت را با قرارداد تطبیق بده. ۳) وضعیت، مرجع قرارداد و تاریخ شروع/پایان را ثبت کن. ۴) اگر قرارداد سقف مصرف دارد Limit را وارد کن. ۵) ذخیره را تأیید کن. تغییر در Audit Log ثبت می‌شود. برای قطع موقت از Suspended استفاده کن؛ رکورد را حذف نکن تا سابقه تجاری باقی بماند.','Customer contracts & entitlements','Safe workflow for paid capability access','1) Select the correct tenant. 2) Match the capability to the signed contract. 3) Record status, contract reference and term. 4) Add a quota only when contracted. 5) Confirm save. Changes are audited. Prefer Suspended over deletion so commercial history remains traceable.',array['قرارداد','دسترسی','entitlement','commerce','seo','ai','theme','contract'], 'critical',array['platform.entitlements','platform.entitlements.status','platform.entitlements.limits'],true,15)
on conflict(article_key) do update set title_fa=excluded.title_fa,summary_fa=excluded.summary_fa,body_fa=excluded.body_fa,title_en=excluded.title_en,summary_en=excluded.summary_en,body_en=excluded.body_en,keywords=excluded.keywords,related_help_keys=excluded.related_help_keys,active=true;
