-- Customer account foundation. Auth identity is global; every commerce profile/address is tenant-scoped.
create table if not exists public.customer_profiles(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,full_name text,phone text,email text,locale text not null default 'fa',marketing_consent boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,user_id));
create table if not exists public.customer_addresses(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,customer_id uuid not null references public.customer_profiles(id) on delete cascade,label text,recipient_name text not null,phone text not null,country_code text not null,province text,city text not null,address_line text not null,postal_code text,is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists customer_default_address_uq on public.customer_addresses(customer_id) where is_default=true;
alter table public.customer_profiles enable row level security;alter table public.customer_addresses enable row level security;
create policy customer_profile_self_select on public.customer_profiles for select to authenticated using(user_id=auth.uid());
create policy customer_profile_self_update on public.customer_profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy customer_address_self_all on public.customer_addresses for all to authenticated using(exists(select 1 from public.customer_profiles p where p.id=customer_id and p.tenant_id=customer_addresses.tenant_id and p.user_id=auth.uid())) with check(exists(select 1 from public.customer_profiles p where p.id=customer_id and p.tenant_id=customer_addresses.tenant_id and p.user_id=auth.uid()));
-- Link historical/future orders to an authenticated customer without removing immutable purchase snapshots.
alter table public.orders add column if not exists customer_id uuid references public.customer_profiles(id) on delete set null;
create index if not exists orders_customer_history_idx on public.orders(tenant_id,customer_id,created_at desc);
create or replace function public.customer_order_history(p_tenant uuid) returns setof public.orders language sql security invoker set search_path=public as $$select o.* from public.orders o join public.customer_profiles p on p.id=o.customer_id and p.tenant_id=o.tenant_id where o.tenant_id=p_tenant and p.user_id=auth.uid() order by o.created_at desc$$;
grant execute on function public.customer_order_history(uuid) to authenticated;
insert into public.admin_help_items(help_key,title_fa,body_fa,warning_fa,title_en,body_en,warning_en,active) values
('customers.account','حساب مشتری','مشتری می‌تواند پروفایل شخصی، زبان و اطلاعات تماس خودش را در همان فروشگاه مدیریت کند. اطلاعات هر فروشگاه از Tenantهای دیگر جدا می‌ماند.','مدیر نباید اطلاعات مشتری یک Tenant را در Tenant دیگر مشاهده یا استفاده کند.','Customer account','Customers can manage their profile, language and contact information for the current store. Customer data remains isolated from other tenants.','Customer information from one tenant must never be exposed or reused in another tenant.',true),
('customers.addresses','دفترچه آدرس','مشتری می‌تواند چند آدرس ذخیره کند و یک آدرس پیش‌فرض داشته باشد تا Checkoutهای بعدی سریع‌تر شوند. سفارش قبلی همچنان Snapshot آدرس زمان خرید را نگه می‌دارد.','ویرایش آدرس ذخیره‌شده نباید آدرس ثبت‌شده روی سفارش‌های قبلی را تغییر دهد.','Address book','Customers can save multiple addresses and choose one default address for faster future checkout. Existing orders keep the address snapshot captured at purchase time.','Editing a saved address must never rewrite the address stored on previous orders.',true),
('customers.order_history','تاریخچه سفارش مشتری','مشتری واردشده فقط سفارش‌هایی را می‌بیند که در همین فروشگاه به حساب خودش متصل شده‌اند؛ وضعیت پرداخت، اجرا، ارسال و مرجوعی می‌تواند از این بخش نمایش داده شود.','دسترسی به سفارش باید در سرور با Tenant و هویت کاربر کنترل شود؛ مخفی‌کردن در رابط کاربری کافی نیست.','Customer order history','A signed-in customer sees only orders linked to their own account in the current store. Payment, fulfillment, shipment and return progress can be presented here.','Order access must be enforced server-side by tenant and user identity; hiding data in the UI is not sufficient.',true)
on conflict(help_key) do update set title_fa=excluded.title_fa,body_fa=excluded.body_fa,warning_fa=excluded.warning_fa,title_en=excluded.title_en,body_en=excluded.body_en,warning_en=excluded.warning_en,active=true;
